### ISSUE TITLE
Cannot find module './_checkGlobal' when running my tests

### ISSUE THREAD

**Issue by MiguhRuiz** [avajs/ava#1016]
There is an error running my tests.

### Test Source

```js
'use strict'

const test = require('ava')
const r = require('rethinkdb')
const Db = require('..')
const uuid = require('uuid-base62')
const fixtures = require('./fixtures/')

test.beforeEach('setup database', async t => {
  const dbName = `bettercode_${uuid.v4()}`
  const db = new Db({ db: dbName, setup: true })
  await db.connect()
  t.context.db = db
  t.context.dbName = dbName
  t.true(db.connected, 'should be connected')
})

test.afterEach.always('cleanup database', async t => {
  let db = t.context.db
  let dbName = t.context.dbName

  await db.disconnect()
  t.false(db.connected, 'should be disconnected')

  let conn = await r.connect({})
  await r.dbDrop(dbName).run(conn)
})

test('GET a project', async t => {
  let db = t.context.db

  t.is(typeof db.getProject, 'function', 'getProject is a function')

  let project = fixtures.getProject()
  let saved = await db.postProject(project)
  let result = await db.getProject(saved.publicId)

  t.deepEqual(saved, result)

  t.throws(db.getProject('foo'), /not found/)

})

test('GET all projects', async t => {
  let db = t.context.db

  t.is(typeof db.getProjects, 'function', 'getProjects is a function')

  let projects = fixtures.getProjects(3)
  let saveProjects = projects.map(project => db.postProject(project))
  let created = await Promise.all(saveProjects)
  let result = await db.getProjects()

  t.is(typeof result, 'object', 'Result is an object')

})

test('POST a project', async t => {
  let db = t.context.db

  t.is(typeof db.postProject, 'function', 'postProject is a function')

  let body = fixtures.getProject()

  let request = await db.postProject(body)

  t.is(request.description, body.description)
  t.is(request.projectImage, body.projectImage)
  t.is(request.subtitle, body.subtitle)
  t.is(request.title, body.title)
  t.is(typeof request.creator, 'string')
  t.truthy(request.createdAt)
})

test('UPDATE a project', async t => {
  let db = t.context.db

  t.is(typeof db.updateProject, 'function', 'updateProject is a function')

  let project = fixtures.getProject()
  let saved = await db.postProject(project)
  let change = await fixtures.updateObject()
  let result = await db.updateProject(saved.id, change)

  t.deepEqual(result.replaced, 1)

})

test('DELETE a project', async t => {
  let db = t.context.db

  t.is(typeof db.deleteProject, 'function', 'deleteProject is a function')

  let project = fixtures.getProject()
  let saved = await db.postProject(project)
  let result = await db.deleteProject(project.id)

  t.deepEqual(result.deleted, 1)

})

```

### Error Message & Stack Trace

```
miguhruiz@MacBook-de-Miguh: ~/Dropbox/dev/bettercode-[fa4c8fc]  17:48
> npm test

> bettercode-db@1.2.1 test /Users/miguhruiz/Dropbox/dev/bettercode-db
> ava --verbose


Uncaught Exception: test/project.js
  Error: Cannot find module './_checkGlobal'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/miguhruiz/Dropbox/dev/bettercode-db/node_modules/lodash/_root.js:1:81)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/miguhruiz/Dropbox/dev/bettercode-db/node_modules/lodash/_coreJsData.js:1:74)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)



  0 tests passed [17:49:07]
  1 uncaught exception

npm ERR! Test failed.  See above for more details.
```
### Command-Line Arguments

```
ava --verbose
```

## Environment

```
Node.js v6.4.0
darwin 16.0.0
ava 0.15.2
npm 3.10.3
```

**Comment by MiguhRuiz** [comment]
I've solved in reinstalling ava.
