### ISSUE TITLE
How to debug using chrome?

### ISSUE THREAD

**Issue by RyanAtViceSoftware** [avajs/ava#1021]
I was just looking for guidance on how to debug. I've read through the various issues here and I see that you can use WebStorm but not everyone on my team uses WebStorm so I wanted a chrome devtools based approach. I was trying to use node debugger as shown below but I keep getting port errors. What am I doing wrong? Is there a better approach?

```
Ryans-MacBook-Pro:zen-board-redux ryanvice$ node --debug=3000 node_modules/.bin/ava --serial src/components/common/forms/FormElement.test.js
Debugger listening on port 3000
Error: listen EADDRINUSE :::3000
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at Agent.Server._listen2 (net.js:1250:14)
    at listen (net.js:1286:10)
    at Agent.Server.listen (net.js:1382:5)
    at Object.start (_debug_agent.js:21:9)
    at startup (node.js:70:44)
    at node.js:968:3
```

**Comment by novemberborn** [comment]
@RyanAtViceSoftware this doesn't work due to how AVA spawns different processes when running the tests. There's some discussion in #929.
