### ISSUE TITLE
Unexpected token export/import .

### ISSUE THREAD

**Issue by vimniky** [avajs/ava#1093]
Hi ! I'm quite new to  ava. I run into this error when using ava:
<br/>

(function (exports, require, module, __filename, __dirname) { export default 'hello';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)
    at loader (/Users/vimniky/projects/advanced-boilerplate/node_modules/babel-register/lib/node.js:144:5)
    at require.extensions.(anonymous function) (/Users/vimniky/projects/advanced-boilerplate/node_modules/babel-register/lib/node.js:154:7)
    at extensions.(anonymous function) (/Users/vimniky/projects/advanced-boilerplate/node_modules/require-precompiled/index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/vimniky/projects/advanced-boilerplate/node_modules/ava/lib/test-worker.js:92:3)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/vimniky/projects/advanced-boilerplate/src/shared/test/configstore.test.js:3:1)
    at Module._compile (module.js:556:32)
    at extensions.(anonymous function) (/Users/vimniky/projects/advanced-boilerplate/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/vimniky/projects/advanced-boilerplate/node_modules/ava/lib/test-worker.js:92:3)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/vimniky/projects/advanced-boilerplate/node_modules/ava/lib/test-worker.js:96:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
<br/>

Here's my ava configuration
// package.json
```json
{
    //...............
  "ava": {
    "require": [
      "./setup-test-env.js"
    ],
    "verbose": true,
    "babel": {
      "presets": [
        "latest",
        "react",
        "stage-0"
      ]
    }
  },
  // ......
}
```
// setup-test-env.js

```javascript
require('babel-register')
require('babel-polyfill')
global.document = require('jsdom').jsdom('<body></body>')
global.window = document.defaultView
global.navigator = window.navigator

```
// a.js
```javascript

export default 'hello'

```

// a.test.js
```javascript
import test from 'ava'
import a from './a'
test('hello', t => {
  t.is(a, 'hello', 'a === hello')
})
```

Do I have missed something in my configuration ?

**Comment by neverfox** [comment]
Do you have an ava config in your package.json? For example,

```
  "ava": {
    "files": [
      "test/*.spec.js"
    ],
    "tap": true,
    "babel": "inherit",
    "require": [
      "babel-register"
    ]
  }
```

**Comment by dlebedynskyi** [comment]
Have same exact issue  if babel is not specified as inherit - ava fails to compile

**Comment by novemberborn** [comment]
> Have same exact issue if babel is not specified as inherit - ava fails to compile

@dlebedynskyi Could you elaborate? How did you specify `babel` before?

**Comment by dlebedynskyi** [comment]
@novemberborn will try to do soon. Thanks for tracking this
