### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by cliguo** [avajs/ava#1149]
bash-3.2$ ava test/users.js
/Users/wind/Documents/node-projects/phenix/kxzg-dao/pg/db.js:21
        async findById(table, id, columns) {
              ^^^^^^^^
SyntaxError: Unexpected identifier
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Module._extensions..js (module.js:580:10)
    at extensions.(anonymous function) (/usr/local/lib/node_modules/ava/node_modules/require-precompiled/index.js:16
:3)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/ava/lib/process-adapter.
js:104:4)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/wind/Documents/node-projects/phenix/kxzg-dao/index.js:4:12)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at extensions.(anonymous function) (/usr/local/lib/node_modules/ava/node_modules/require-precompiled/index.js:16
:3)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/local/lib/node_modules/ava/lib/process-adapter.
js:104:4)
    at Module.load (module.js:488:32)

  1 exception

  ✖ test/users.js exited with a non-zero exit code: 1

db.js:21#
```
async findById(table, id, columns) {
		try {
			var sql = 'SELECT * FROM ${table~} WHERE id=${id}';
			if(Array.isArray(columns)){
				sql = 'SELECT ${columns^} FROM ${table~} WHERE id=${id}';
				columns = columns.map(pgp.as.name).join();
			}
			let one = await this.db.one(sql, {
				columns: columns,
				table: table,
				id: id
			});

			return result.genOkRs(one);
		} catch (e) {
			return e.code === 0 ? result.genOkRs(null) : result.genDbFailRs(e);
		}
	}
```
test/users.js#
```
import Dao from '../index'
import test from 'ava';

const dao = new Dao();
dao.build();
const accessor = dao.accessors['users'];

test('findOne', async t => {
    let rs = await accessor.findOne({mobile: '18657183613'});
    console.log(rs);
	t.true(rs.result.success);
});
```

## Environment

```
node v7.2.1
ava  v0.17.0
npm v3.10.10
```

**Comment by mightyiam** [comment]
Perhaps by `async findById(table, id, columns) {` you actually mean `await findById(table, id, columns) {`?

**Comment by eric7578** [comment]
same issue here
In my case, I try to strip babel, so I use node v7.2.0
in my source code:

```
exports.create = async function (mail, password) {
...
}
```

But I got the following error

```
/Volumes/HD/projects/stores/mailIdentity.js:3
exports.create = async function (mail, password) {
                       ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
```

**Comment by novemberborn** [comment]
It should be `async function findById()`.

This is unrelated to AVA so I'm closing this issue.
