### ISSUE TITLE
running ava test throws 'await is a reserved word'

### ISSUE THREAD

**Issue by Travmatth** [avajs/ava#1167]
Bug Report
- while processing a file being tested, ava throws 'await is a reserved word'

Versions
OSX 10.11.6
Node v6.1.0
npm 3.8.9
yarn 0.17.9
ava 0.17.0

Bug Description
- The following command throws an error, preventing my tests from being fully run
$yarn test
- Error:
/Users/$USER/node_modules/babel-core/lib/transformation/file/index.js:600
      throw err;
      ^

SyntaxError: /Users/$USER/src/localweather/index.js: await is a reserved word (39:29)
  37 |       // Call API, parse response
  38 |       try {
> 39 |         const weather: any = await fetchWeather(resource)
     |                              ^
  40 | 
  41 |       // Call API, parse response, generate data, update DOM
  42 |       // updateDOM(weather, cells)
    at Parser.pp$5.raise (/Users/$USER/node_modules/babylon/lib/index.js:4246:13)
    at Parser.pp$3.checkReservedWord (/Users/$USER/node_modules/babylon/lib/index.js:4137:10)
    at Parser.pp$3.parseIdentifier (/Users/$USER/node_modules/babylon/lib/index.js:4115:12)
    at Parser.pp$3.parseExprAtom (/Users/$USER/node_modules/babylon/lib/index.js:3484:21)
    at Parser.pp$3.parseExprSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (/Users/$USER/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/$USER/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/$USER/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:5694:20)
    at Parser.pp$1.parseVar (/Users/$USER/node_modules/babylon/lib/index.js:2205:24)
    at Parser.pp$1.parseVarStatement (/Users/$USER/node_modules/babylon/lib/index.js:2036:8)
    at Parser.pp$1.parseStatement (/Users/$USER/node_modules/babylon/lib/index.js:1729:19)
    at Parser.parseStatement (/Users/$USER/node_modules/babylon/lib/index.js:5218:22)
    at Parser.pp$1.parseBlockBody (/Users/$USER/node_modules/babylon/lib/index.js:2133:21)
    at Parser.pp$1.parseBlock (/Users/$USER/node_modules/babylon/lib/index.js:2114:8)
    at Parser.pp$1.parseTryStatement (/Users/$USER/node_modules/babylon/lib/index.js:2008:21)
    at Parser.pp$1.parseStatement (/Users/$USER/node_modules/babylon/lib/index.js:1722:19)
    at Parser.parseStatement (/Users/$USER/node_modules/babylon/lib/index.js:5218:22)
    at Parser.pp$1.parseBlockBody (/Users/$USER/node_modules/babylon/lib/index.js:2133:21)
    at Parser.pp$1.parseBlock (/Users/$USER/node_modules/babylon/lib/index.js:2114:8)
    at Parser.pp$3.parseFunctionBody (/Users/$USER/node_modules/babylon/lib/index.js:3998:22)
    at Parser.parseFunctionBody (/Users/$USER/node_modules/babylon/lib/index.js:5205:20)
    at Parser.pp$3.parseArrowExpression (/Users/$USER/node_modules/babylon/lib/index.js:3977:8)
    at Parser.pp$3.parseExprAtom (/Users/$USER/node_modules/babylon/lib/index.js:3501:21)
    at Parser.pp$3.parseExprSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (/Users/$USER/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/$USER/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/$USER/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:5694:20)
    at Parser.pp$3.parseExprListItem (/Users/$USER/node_modules/babylon/lib/index.js:4101:16)
    at Parser.parseExprListItem (/Users/$USER/node_modules/babylon/lib/index.js:5425:24)
    at Parser.pp$3.parseCallExpressionArguments (/Users/$USER/node_modules/babylon/lib/index.js:3410:20)
    at Parser.pp$3.parseSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3370:31)
    at Parser.pp$3.parseExprSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3341:15)
    at Parser.pp$3.parseMaybeUnary (/Users/$USER/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/$USER/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/$USER/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:5694:20)
    at Parser.pp$3.parseExpression (/Users/$USER/node_modules/babylon/lib/index.js:3143:19)
    at Parser.pp$1.parseStatement (/Users/$USER/node_modules/babylon/lib/index.js:1774:19)
    at Parser.parseStatement (/Users/$USER/node_modules/babylon/lib/index.js:5218:22)
    at Parser.pp$1.parseBlockBody (/Users/$USER/node_modules/babylon/lib/index.js:2133:21)
    at Parser.pp$1.parseBlock (/Users/$USER/node_modules/babylon/lib/index.js:2114:8)
    at Parser.pp$3.parseFunctionBody (/Users/$USER/node_modules/babylon/lib/index.js:3998:22)
    at Parser.parseFunctionBody (/Users/$USER/node_modules/babylon/lib/index.js:5205:20)
    at Parser.pp$3.parseArrowExpression (/Users/$USER/node_modules/babylon/lib/index.js:3977:8)
    at Parser.pp$3.parseParenAndDistinguishExpression (/Users/$USER/node_modules/babylon/lib/index.js:3687:17)
    at Parser.pp$3.parseExprAtom (/Users/$USER/node_modules/babylon/lib/index.js:3545:19)
    at Parser.pp$3.parseExprSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3331:19)
    at Parser.pp$3.parseMaybeUnary (/Users/$USER/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/$USER/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/$USER/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:5694:20)
    at Parser.pp$3.parseExprListItem (/Users/$USER/node_modules/babylon/lib/index.js:4101:16)
    at Parser.parseExprListItem (/Users/$USER/node_modules/babylon/lib/index.js:5425:24)
    at Parser.pp$3.parseCallExpressionArguments (/Users/$USER/node_modules/babylon/lib/index.js:3410:20)
    at Parser.pp$3.parseSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3370:31)
    at Parser.pp$3.parseExprSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3341:15)
    at Parser.pp$3.parseMaybeUnary (/Users/$USER/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/$USER/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/$USER/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:5694:20)
    at Parser.pp$3.parseExpression (/Users/$USER/node_modules/babylon/lib/index.js:3143:19)
    at Parser.pp$1.parseStatement (/Users/$USER/node_modules/babylon/lib/index.js:1774:19)
    at Parser.parseStatement (/Users/$USER/node_modules/babylon/lib/index.js:5218:22)
    at Parser.pp$1.parseBlockBody (/Users/$USER/node_modules/babylon/lib/index.js:2133:21)
    at Parser.pp$1.parseBlock (/Users/$USER/node_modules/babylon/lib/index.js:2114:8)
    at Parser.pp$3.parseFunctionBody (/Users/$USER/node_modules/babylon/lib/index.js:3998:22)
    at Parser.parseFunctionBody (/Users/$USER/node_modules/babylon/lib/index.js:5205:20)
    at Parser.pp$3.parseArrowExpression (/Users/$USER/node_modules/babylon/lib/index.js:3977:8)
    at Parser.pp$3.parseAsyncArrowFromCallExpression (/Users/$USER/node_modules/babylon/lib/index.js:3427:15)
    at Parser.parseAsyncArrowFromCallExpression (/Users/$USER/node_modules/babylon/lib/index.js:5623:20)
    at Parser.pp$3.parseSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3377:21)
    at Parser.pp$3.parseExprSubscripts (/Users/$USER/node_modules/babylon/lib/index.js:3341:15)
    at Parser.pp$3.parseMaybeUnary (/Users/$USER/node_modules/babylon/lib/index.js:3311:19)
    at Parser.pp$3.parseExprOps (/Users/$USER/node_modules/babylon/lib/index.js:3241:19)
    at Parser.pp$3.parseMaybeConditional (/Users/$USER/node_modules/babylon/lib/index.js:3218:19)
    at Parser.pp$3.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:3181:19)
    at Parser.parseMaybeAssign (/Users/$USER/node_modules/babylon/lib/index.js:5694:20)
    at Parser.pp$1.parseVar (/Users/$USER/node_modules/babylon/lib/index.js:2205:24)

Severity
Major

Steps to Reproduce
running the following at the command line:
$ yarn test

Actual Behavior
When run, the pages that use async/await syntax (localweather/index.js) crash (see stdout file), while the other pages perform as expected (see passing). 

Expected Behavior
The tests (originally refactored from mocha) should execute with a pass || fail.

Troubleshooting/Testing Steps Attempted
- the advice i've found in ava's docs indicate i should add an 'ava' key to the projects package.json (https://github.com/avajs/ava/blob/58a2e6803f74fa29d601e019b22f6a0b945c3544/docs/recipes/babelrc.md)
- this has not worked, it yields the error i'm currently grappling with

Workaround
- None currently, will need to uninstall ava and go back to mocha. 

- I've extracted the relevant files (.babelrc, etc) to a gist
https://gist.github.com/Travmatth/10b0b7b2db3e9d85d80e7360e78b21a1

- the project is located on github:
https://github.com/Travmatth/resume-static-aws/

**Comment by mightyiam** [comment]
The issue may be that [the callback for `getCurrentPosition`](https://gist.github.com/Travmatth/10b0b7b2db3e9d85d80e7360e78b21a1#file-localweather-index-js-L6) is not an `async` function. I've very little experience with `async` functions, though.

**Comment by Travmatth** [comment]
To test the theory out I cleaned up my codebase and stubbed out as much as I can, and even without the window.navigator code I'm still throwing an error. Interestingly enough, when i stub out the line `const weather: any = await fetchWeather(resource)` my code will work as expected, even with the 'async' keyword above it. My current test is here: https://github.com/Travmatth/resume-static-aws/blob/master/src/localweather/index.spec.js

**Comment by mightyiam** [comment]
What about what I suggested?

**Comment by Travmatth** [comment]
Sorry, I misread your comment as meaning the tests getCurrentPosition() method had something to do with the error. You are correct, the callback for that function needed to be marked async as well. Doing so corrected the error.
