### ISSUE TITLE
Does not work with VueJS?

### ISSUE THREAD

**Issue by leonardovilarinho** [avajs/ava#1200]
I'm trying to test components of the *Vue JS 2*  with the help of *AVA*, but I am having the following error:

    exited with a non-zero exit code: 1

Follows the code of my test:

```
import resource from '../src/components/t'

import ava from 'ava'

ava('meu teste', t => {
    t.deepEqual([1], [1])
})
```

`t.js`:

```
export default {
    test: 'my msg'
}
```

What could be the error?

The VueJS is developed using ES5, this could be the problem? Is there any way I can fix this? I really wanted to use the AVA.

I tried installing the nyc but the error continues:

PS D:\projetos\php\public\tcc\spac> npm test
```

> spa@1.0.0 test D:\projetos\php\public\tcc\spac
> nyc ava

D:\projetos\php\public\tcc\spac\src\components\t.js:1
(function (exports, require, module, __filename, __dirname) { export default {
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at exports.runInThisContext (vm.js:78:16)
    at Object.vm.runInThisContext (D:\Projetos\PHP\public\tcc\spac\node_modules\nyc\node_modules\istanbul-lib-hook\lib\h
ook.js:141:16)
    at Module._compile (module.js:543:28)
    at Module.replacementCompile (D:\Projetos\PHP\public\tcc\spac\node_modules\nyc\node_modules\append-transform\index.j
s:58:13)
    at module.exports (D:\Projetos\PHP\public\tcc\spac\node_modules\nyc\node_modules\default-require-extensions\js.js:8:
9)
    at D:\Projetos\PHP\public\tcc\spac\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at extensions.(anonymous function) (D:\Projetos\PHP\public\tcc\spac\node_modules\require-precompiled\index.js:16:3)
    at D:\Projetos\PHP\public\tcc\spac\node_modules\nyc\node_modules\append-transform\index.js:62:4
    at require.extensions.(anonymous function) (D:\Projetos\PHP\public\tcc\spac\node_modules\ava\lib\process-adapter.js:
104:4)
    at Object.<anonymous> (D:\Projetos\PHP\public\tcc\spac\node_modules\nyc\node_modules\append-transform\index.js:62:4)

    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (D:\projetos\php\public\tcc\spac\test\init.js:1:1)

  1 exception

  × test\init.js exited with a non-zero exit code: 1

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|
npm ERR! Test failed.  See above for more details.
PS D:\projetos\php\public\tcc\spac>
```

**Comment by sindresorhus** [comment]
AVA only transpiles your test files, not your source. If you want AVA to also handle source files, read this guide: https://github.com/avajs/ava/blob/b24495d5f495abee798589c7c0b91202f4207064/docs/recipes/babelrc.md#transpiling-sources

**Comment by leonardovilarinho** [comment]
I couldn't make it work :(
thanks anyway, I'll see if I can find another solution

**Comment by Austio** [comment]
@leonardovilarinho I was able to get this working with adding this to my file package.json

```
 "ava": {
    "require": [
      "babel-register"
    ]
  },
  "babel": {
    "presets": [
      "es2015"
    ]
  }
```
