### ISSUE TITLE
Non string assertion messages throw an error

### ISSUE THREAD

**Issue by vaelinn123** [avajs/ava#1235]
## Description

This could just be that the [documentation](https://github.com/avajs/ava#assertions) needs updated to reflect that the assertion messages be string only, it does not hamper me in any way I just wanted to highlight that it does not gracefully fail when you do not use a string as an assertion message. 

Given an assertion with a failure message:

```js
t.true(0, 10)
```
When there is a failure I expect it to display the failure message.

### Test Source

```js
const test = require('ava');
test('Fails gracefully with "10" failure message', t => {
  t.true(0, 10);
});
```

### Error Message & Stack Trace

```
TypeError: test.error.message.trim is not a function
at /Users/tyler.main/Workspace/users-core/node_modules/ava/lib/reporters/verbose.js:120:28
at Array.forEach (native)
at VerboseReporter.finish (/Users/tyler.main/Workspace/users-core/node_modules/ava/lib/reporters/verbose.js:98:20)
at Logger.finish (/Users/tyler.main/Workspace/users-core/node_modules/ava/lib/logger.js:38:28)
at /Users/tyler.main/Workspace/users-core/node_modules/ava/lib/cli.js:167:12
From previous event:
at Object.exports.run.api.on.api.run.then [as run] (/Users/tyler.main/Workspace/users-core/node_modules/ava/lib/cli.js:166:5)
at Object.<anonymous> (/Users/tyler.main/Workspace/users-core/node_modules/ava/cli.js:22:24)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Object.<anonymous> (/Users/tyler.main/.welo/nitpicker-support/packages/2.0.6/node_modules/ava/cli.js:13:2)
at Module._compile (module.js:409:26)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Function.Module.runMain (module.js:441:10)
at startup (node.js:139:18)
at node.js:968:3
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
      "test-dirs": [
        "test/unit/",
        "test/contract/"
      ]
    }
}
```

### Command-Line Arguments
```
ava test/contract/*.js -v 
```

## Environment
Node.js v4.4.2
darwin 15.6.0
ava: 0.18.1
npm: 3.9.2

**Comment by novemberborn** [comment]
Yep, see #1125. There is an in-progress PR at #1174.
