### ISSUE TITLE
Errors coming from an iterator have an incorrect source file

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1269]
```js
import test from 'ava'

test(() => {
  Array.from({
    *[Symbol.iterator] () {
      throw new Error('Boom')
    }
  })
})
```

Results in:

```
Error: ENOENT: no such file or directory, open '/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.yTcChE8g5j/private/var/folders/_6/p8qxp_3n62zg9081tvb0lcc80000gn/T/tmp.yTcChE8g5j/Object.[Symbol.iterator] (file.js'
    at Object.fs.openSync (fs.js:558:18)
    at Object.fs.readFileSync (fs.js:468:33)
    at module.exports (/Users/mark/GitHub/avajs/ava/lib/code-excerpt.js:15:20)
    at runStatus.errors.forEach (/Users/mark/GitHub/avajs/ava/lib/reporters/mini.js:191:22)
    at Array.forEach (native)
    at MiniReporter.finish (/Users/mark/GitHub/avajs/ava/lib/reporters/mini.js:178:21)
    at Logger.finish (/Users/mark/GitHub/avajs/ava/lib/logger.js:38:28)
    at api.run.then.runStatus (/Users/mark/GitHub/avajs/ava/lib/cli.js:170:12)
```

Follow-up from https://github.com/avajs/ava/issues/1231.

**Comment by novemberborn** [comment]
This is an issue in `stack-utils`. Fix in https://github.com/tapjs/stack-utils/pull/27.
