### ISSUE TITLE
t.fail([message]) out of expect? still pass test

### ISSUE THREAD

**Issue by axetroy** [avajs/ava#1306]
## Description

Run some async task, if catch error, then run ``t.fail()``

but I found, even i apply ``t.fail()``, it still be success

why?

### Test Source

```js
const test = require('ava');
const co = require('co');
const doSomethingAsync = function () {
  throw new Error('This is an unExpect Error');
};

test('should concat input', (t) => {
  co(function *() {
    yield doSomethingAsync();
    console.log('start run pass');
    t.pass();
  }).catch(function (err) {
    console.error('catch error:');
    console.error(err);
    t.fail(err);
    console.log('exec fail method');
  });
});
```

### Error Message & Stack Trace

```
$ npm run test

> @axetroy/gpm@5.4.1 test C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js
> cross-env NODE_ENV=development ava

catch error:
Error: This is an unExpect Error
    at doSomethingAsync (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\test\gpm.test.js:7:9)
    at C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\test\gpm.test.js:12:11
    at next (native)
    at onFulfilled (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\co\index.js:65:19)
    at C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\co\index.js:54:5
    at co (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\co\index.js:50:10)
    at Test.t [as fn] (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\test\gpm.test.js:11:3)
    at Test._run (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\test.js:185:15)
    at Test.run (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\test.js:228:18)
    at Sequence.run (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\sequence.js:29:33)
    at Concurrent._runTest (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\concurrent.js:45:23)
    at Array.map (native)
    at Concurrent.run (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\concurrent.js:25:25)
    at Sequence.run (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\sequence.js:29:33)
    at Sequence.run (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\sequence.js:29:33)
    at Runner.run (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\runner.js:153:55)
    at process.on.options (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\main.js:73:10)
    at emitOne (events.js:96:13)
    at process.emit (events.js:188:7)
    at process.on.message (C:\Users\axetroy\gpmx\github.com\gpmer\gpm.js\node_modules\ava\lib\test-worker.js:66:10)
    at emitTwo (events.js:106:13)
    at process.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
exec fail method

  1 passed

```

### Config

Not configure

### Command-Line Arguments

```
cross-env NODE_ENV=development ava
```

## Relevant Links

Not yet

## Environment
Node.js v6.10.0
win32 10.0.14393
ava 0.18.2
npm 3.10.10

**Comment by sindresorhus** [comment]
You're doing async work in a sync test. Per the documentation, if you want to do async work, you either need to return a promise from the test, use an async function (recommended) or generator function as the test body, or use `test.cb()`.

**Comment by axetroy** [comment]
I have found it in documentation, I'm curious about why don't work.

sync work not depend on fail method.

anyway, Thanks.

**Comment by sindresorhus** [comment]
By the time you call `t.fail()` AVA has already considered the test function done, since all the synchronous code has run.
