### ISSUE TITLE
Ava throws `Cannot read property 'moduleName' of null` since `0.19.0`

### ISSUE THREAD

**Issue by kdex** [avajs/ava#1360]
## Description

Upgrading `ava` from `0.18.2` to `0.19.0` broke the tests in [ws-promise](https://github.com/kdex/ws-promise). Running ava will cause `Cannot read property 'moduleName' of null`.

This still happens in `0.19.1`.

### Test Source

No tests are required to reproduce; commenting out all tests in `ws-promise` results in the same error.

### Error Message & Stack Trace

```js
╭─kdex@punchy-old  ~/dev/wp  ‹master› 
╰─$ $(npm bin)/ava                                                                                                                                    1 ↵

  1 exception

  Uncaught Exception
  TypeError: /home/kdex/dev/wp/test/Client.js: Cannot read property 'moduleName' of null
    at getRuntimeModuleName (/home/kdex/dev/wp/node_modules/babel-plugin-transform-runtime/lib/index.js:10:16)
    at PluginPass.pre (/home/kdex/dev/wp/node_modules/babel-plugin-transform-runtime/lib/index.js:21:24)
    at File.call (/home/kdex/dev/wp/node_modules/babel-core/lib/transformation/file/index.js:628:18)
    at File.transform (/home/kdex/dev/wp/node_modules/babel-core/lib/transformation/file/index.js:544:12)
    at /home/kdex/dev/wp/node_modules/babel-core/lib/transformation/pipeline.js:50:19
    at File.wrap (/home/kdex/dev/wp/node_modules/babel-core/lib/transformation/file/index.js:564:16)
    at Pipeline.transform (/home/kdex/dev/wp/node_modules/babel-core/lib/transformation/pipeline.js:47:17)
    at CachingPrecompiler._transform (/home/kdex/dev/wp/node_modules/ava/lib/caching-precompiler.js:58:24)
    at transform (/home/kdex/dev/wp/node_modules/caching-transform/index.js:43:10)
    at CachingPrecompiler.transform (/home/kdex/dev/wp/node_modules/caching-transform/index.js:60:17)
    at CachingPrecompiler.precompileFile (/home/kdex/dev/wp/node_modules/ava/lib/caching-precompiler.js:39:9)
    at Api._runFile (/home/kdex/dev/wp/node_modules/ava/api.js:57:33)
    at resolve (/home/kdex/dev/wp/node_modules/ava/api.js:240:24)
From previous event:
    at Api._runWithoutPool (/home/kdex/dev/wp/node_modules/ava/api.js:237:5)
    at _setupPrecompiler.then.then (/home/kdex/dev/wp/node_modules/ava/api.js:164:23)
```

### Config

```json
{
  "ava": {
    "require": "babel-register",
    "babel": "inherit"
  }
}
```

### Command-Line Arguments

```bash
$(npm bin)/ava
```

## Relevant Links

- [ws-promise](https://github.com/kdex/ws-promise) (ava worked at 1.0.3)

## Environment

Node.js v7.7.3
linux 4.10.9-1-ARCH
0.19.1
4.1.1

**Comment by novemberborn** [comment]
What is your Babel config? The error comes from `babel-plugin-transform-runtime` which isn't used by AVA itself (not since `0.18` actually).

> ws-promise (ava worked at 1.0.3)

What do you mean by "ava worked at 1.0.3"?

**Comment by kdex** [comment]
Here's my Babel configuration:

```js
{
        "presets": [
                [
                        "env", {
                                "targets": {
                                        "node": true
                                }
                        }
                ],
                "stage-0"
        ],
        "plugins": [
                ["module-resolver", {
                        "root": ["./"]
                }]
        ]
}
```

By "ava worked at 1.0.3", I was referring to `ws-promise@1.0.3`. Back in `ws-promise@1.0.3`, the project had used `ava@0.18.2`, which didn't throw the error.

In other words, if I `git reset` to `ws-promise@1.0.3` and then `npm install ava@0.19.0`, the error from above arises.

I use `babel-plugin-transform-runtime` in `ws-promise` so that I can ship a transpiled version without polluting the user's global environment.

**Comment by novemberborn** [comment]
Sorry, it somehow hadn't clicked that you were using AVA to develop `ws-promise`, I thought it was a dependency!

This is due to a bug in the module we started using in `0.19` to resolve Babel options: https://github.com/novemberborn/hullabaloo-config-manager/issues/10

For now you can work around this by not putting `["transform-runtime"]` in an array, or by specifying an empty options object (`["transform-runtime", {}]`). I'll try and get a fix out soon.

**Comment by kdex** [comment]
@novemberborn Ah, that explains everything; thank you. I'll close this issue in favor of [novemberborn/hullabaloo-config-manager#10](https://github.com/novemberborn/hullabaloo-config-manager/issues/10).

**Comment by novemberborn** [comment]
`hullabaloo-config-manager@1.0.1` is now available.
