### ISSUE TITLE
error when test fails

### ISSUE THREAD

**Issue by uncleGena** [avajs/ava#1370]
## Description

Hi. I really want to use AVA testing framework, but wen test fails it also throw an error. 

### Test Source

```js
import test from 'ava';

test('foo', t => {
	t.pass();
});

test('bar', async t => {
	const bar = Promise.resolve('bars'); 

	t.is(await bar, 'bar');
});

test('my passing test', t => {
	t.pass();
});
```

### Error Message & Stack Trace
this is from file in `~/.npm/logs/`

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'test' ]
2 info using npm@4.2.0
3 info using node@v7.9.0
4 verbose run-script [ 'pretest', 'test', 'posttest' ]
5 info lifecycle energy_strategy@0.0.1~pretest: energy_strategy@0.0.1
6 silly lifecycle energy_strategy@0.0.1~pretest: no script for pretest, continuing
7 info lifecycle energy_strategy@0.0.1~test: energy_strategy@0.0.1
8 verbose lifecycle energy_strategy@0.0.1~test: unsafe-perm in lifecycle true
9 verbose lifecycle energy_strategy@0.0.1~test: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/vagrant/psychea/energy/node_modules/.bin:/home/vagrant/.composer/vendor/bin:/home/vagrant/bin:/home/vagrant/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle energy_strategy@0.0.1~test: CWD: /home/vagrant/psychea/energy
11 silly lifecycle energy_strategy@0.0.1~test: Args: [ '-c', 'ava' ]
12 silly lifecycle energy_strategy@0.0.1~test: Returned: code: 1  signal: null
13 info lifecycle energy_strategy@0.0.1~test: Failed to exec test script
14 verbose stack Error: energy_strategy@0.0.1 test: `ava`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid energy_strategy@0.0.1
16 verbose cwd /home/vagrant/psychea/energy
17 error Linux 4.4.0-51-generic
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "test"
19 error node v7.9.0
20 error npm  v4.2.0
21 error code ELIFECYCLE
22 error errno 1
23 error energy_strategy@0.0.1 test: `ava`
23 error Exit status 1
24 error Failed at the energy_strategy@0.0.1 test script 'ava'.
24 error Make sure you have the latest version of node.js and npm installed.
24 error If you do, this is most likely a problem with the energy_strategy package,
24 error not with npm itself.
24 error Tell the author that this fails on your system:
24 error     ava
24 error You can get information on how to open an issue for this project with:
24 error     npm bugs energy_strategy
24 error Or if that isn't available, you can get their info via:
24 error     npm owner ls energy_strategy
24 error There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

and this is output in terminal 
```
> ava


  2 passed
  1 failed

  bar
  /home/vagrant/psychea/energy/test.js:11

   10:                          
   11:   t.is(await bar, 'bar');
   12: });                      

  Difference:

    "bars"

  Test.<anonymous> (test.js:11:4)
  step (test.js:9:191)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! energy_strategy@0.0.1 test: `ava`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the energy_strategy@0.0.1 test script 'ava'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the energy_strategy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ava
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs energy_strategy
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls energy_strategy
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vagrant/.npm/_logs/2017-04-25T15_12_24_776Z-debug.log
```

### Config 

no config

### Command-Line Arguments
no arguments
only `"scripts": {
    "test": "ava",`

## Environment

Linux Ubuntu 14.04 
Webpack 2
node v7.9.0
npm v4.5.0

```
"ava": "^0.19.1"
```

**Comment by novemberborn** [comment]
This is what `npm` does when a script exits with an error code. (And exiting with an error code is the correct behavior when a test fails.)

The output is less verbose in more recent versions of `npm`. Note that the log file says `2 info using npm@4.2.0`. Try installing the `npm@latest`.

**Comment by uncleGena** [comment]
I've tried. my npm is latest - v4.5.0 and nodejs is latest to v.7.9.0 
Also I've cleared cache and reinstalled node_modules and use command `npm rebuild node-sass`. 
That did not help.

**Comment by novemberborn** [comment]
This is what `npm test` does. Alternatively you can run AVA directly (`./node_modules/.bin/ava`) or install it globally and invoke `ava`.
