### ISSUE TITLE
babel config broken when upgraded from 0.17 -> 0.20 or 0.19

### ISSUE THREAD

**Issue by norama** [avajs/ava#1430]
I have es2015 import keyword as well as jsx in my tests.
My babel config worked fine with ava 0.17, in version 0.19 does not understand es2015 import.
If I omit the babel ocnfig, then cannot interpret jsx. Both worked fine with version 0.17, with configuration below. I have tried all combinations that you have in your docs, did not help.

### Code
```
import ava from 'ava';
import assert from 'assert';

import validateEmail, {validateEmails}  from '../build-next/internals/isEmailValid';


ava.test('single - true', (test) => {
	assert(validateEmail('a@b.com'));
});
```

```
import React from 'react'; // Important: even if not explicitly used, if React is not imported, compile fails

import ava from 'ava';
import assert from 'assert';
import {shallow} from 'enzyme';
import render from 'react-test-renderer';
import Tags from '../build-next/components/Tags';
import TagType from '../build-next/types/TagForType';

const tags = [{id: 1, isFor: 'source', name: 'tag1'}, {id: 2, isFor: 'source', name: 'tag2'}];

ava.test('Tags - assert', t => {
	
	const wrapper = shallow(<Tags tags={tags} tagType={TagType.source} />);
	t.is(wrapper.find('a').length, 2);
});

```

### Error Message & Stack Trace

```
  SyntaxError: C:/WebDev/DataWeps/verboom-app/test/isEmailValid.test.js: Unexpected token import
C:\WebDev\DataWeps\verboom-app\gulpfile.ts:3
import * as path from 'path';
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
   "require": [
      "ignore-styles"
    ],
    "babel": {
        "presets": [
           "es2015",
           "stage-0",
           "react"
        ]
    }
  }
}
```

**Comment by novemberborn** [comment]
What happens if you try:

```json
{
  "ava": {
   "require": [
      "ignore-styles"
    ],
    "babel": {
        "babelrc": false,
        "presets": [
           "es2015",
           "stage-0",
           "react"
        ]
    }
  }
}
```

**Comment by norama** [comment]
Almost solved the problem, but gave a `ReferenceError: regeneratorRuntime is not defined` error so I had to use this as well:
https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined 
I ended up with this config (plus the necessary dev-deps according to the above post):
