### ISSUE TITLE
`t.throws()` with regex not working as expected

### ISSUE THREAD

**Issue by stevenvachon** [avajs/ava#1445]
This fails:
```js
t.throws(() => { throw new TypeError("Invalid URL: http://") }, /^Invalid URL/)
```

... yet:
```js
/^Invalid URL/.test("Invalid URL: http://")
//-> true
```

> `error` can be an error constructor, error message, **regex** matched against the error message, or validation function.

**Comment by sindresorhus** [comment]
Underneath we're using the Node.js core `assert.throws` method and it seems it uses `error.toString()` instead of `error.message` for the regex testing. Yet another reason we should do our own implementation of `throws()`.

```js
assert.throws(() => {
  throw new Error('foobar');
}, /^foo/);
/*
Error: foobar
    at assert.throws (repl:1:29)
    at _tryBlock (assert.js:489:5)
    at _throws (assert.js:510:12)
    at Function.throws (assert.js:540:3)
    at repl:1:8
    at ContextifyScript.Script.runInThisContext (vm.js:44:33)
    at REPLServer.defaultEval (repl.js:239:29)
    at bound (domain.js:301:14)
    at REPLServer.runBound [as eval] (domain.js:314:12)
    at REPLServer.onLine (repl.js:433:10)
*/
```

```js
assert.throws(() => {
  throw new Error('foobar');
}, /^Error: foo/);
//=> undefined
```
