### ISSUE TITLE
resolveCwd.silent is not a function

### ISSUE THREAD

**Issue by rijkvanzanten** [avajs/ava#1458]
## Description
Doing anything with Ava throws a `resolveCwd.silent is not a function` error. This is on a new project with a clean installation of Node (using nvm) and Ava.

### Error Message & Stack Trace

```
/Users/rijk/Development/project/node_modules/import-local/index.js:10
        const localFile = resolveCwd.silent(path.join(pkg.name, relativePath));
                                     ^

TypeError: resolveCwd.silent is not a function
    at module.exports.filename (/Users/rijk/Development/project/node_modules/import-local/index.js:10:31)
    at Object.<anonymous> (/Users/rijk/Development/project/node_modules/ava/cli.js:7:5)    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at module.exports.filename (/Users/rijk/.nvm/versions/node/v8.1.4/lib/node_modules/ava/node_modules/import-local/index.js:16:66)
```

### Command-Line Arguments
Any `ava` command

## Environment
```
Node.js v8.1.4
darwin 16.6.0
-- it errors here as well, same error as above --
5.3.0
```

**Comment by sindresorhus** [comment]
Looks like a deduplication error with npm. You're getting an older version of `resolve-cwd` than specified. Try upgrading to latest Node.js and npm, and if still an issue, open this on the npm issue tracker instead.

**Comment by edouard-lopez** [comment]
@rijkvanzanten could you describe how you solved this ?

**Comment by edouard-lopez** [comment]
Fixed it with:

    npm uninstall ava
    npm install --save-dev ava
