### ISSUE TITLE
ava and chalk

### ISSUE THREAD

**Issue by qaraluch** [avajs/ava#1507]
Using ava and chalk together throw an `TypeError: chalk.stripColor is not a function`.

Stack:
```
J:\scripts\atv-import-split-md\node_modules\ava\lib\concordance-options.js:122
                return chalk.stripColor(value);
                             ^

TypeError: chalk.stripColor is not a function
    at value (J:\scripts\atv-import-split-md\node_modules\ava\lib\concordance-options.js:122:16)
    at baseClone (J:\scripts\atv-import-split-md\node_modules\lodash.clonedeepwith\index.js:844:23)
    at J:\scripts\atv-import-split-md\node_modules\lodash.clonedeepwith\index.js:897:30
    at arrayEach (J:\scripts\atv-import-split-md\node_modules\lodash.clonedeepwith\index.js:140:9)
    at baseClone (J:\scripts\atv-import-split-md\node_modules\lodash.clonedeepwith\index.js:891:3)
    at J:\scripts\atv-import-split-md\node_modules\lodash.clonedeepwith\index.js:897:30
    at arrayEach (J:\scripts\atv-import-split-md\node_modules\lodash.clonedeepwith\index.js:140:9)
    at baseClone (J:\scripts\atv-import-split-md\node_modules\lodash.clonedeepwith\index.js:891:3)
    at cloneDeepWith (J:\scripts\atv-import-split-md\node_modules\lodash.clonedeepwith\index.js:1409:10)
    at Object.<anonymous> (J:\scripts\atv-import-split-md\node_modules\ava\lib\concordance-options.js:120:20)
(...)
```
$ npm ava --version  -> 0.20.0
$ npm chalk --version  -> 2.1.0
$ node --version  -> v8.1.3
$ npm --version  -> v5.0.0

Configs:
```
    "start:test": "npm run prepublish -s && npm run test -s",
    "prepublish": "babel src --out-dir=dist",
    "test": "ava --verbose \"test/*.test.js\""
```

OS: Windows 7

**Comment by qaraluch** [comment]
I guess, It will be handled by commit: https://github.com/Collinslenjo/ava/pull/3/commits/7a28c595a5cfe06254359629be96f181795a0937

**Comment by sindresorhus** [comment]
This looks like a problem with npm. I've seen this many times now. Try upgrading to the latest npm and reinstall.

**Comment by qaraluch** [comment]
After reinstalling npm to v. 5.4.0 it works. Thanks.

**Comment by novemberborn** [comment]
> This looks like a problem with npm.

Yea. This seems to use AVA 0.20.0, which depends on `chalk@1`. `stripColor` is removed in `chalk@2`, so AVA is using the wrong `chalk` version. Which is a problem with the installation, and thus npm.

**Comment by ORESoftware** [comment]
npm version 5.x strikes again lol
