### ISSUE TITLE
 Cannot read property 'length' of undefined when using lodash in tests

### ISSUE THREAD

**Issue by poppein** [avajs/ava#1520]
## Description

When importing lodash and using it in a test, an exception `Cannot read property 'length' of undefined
` is raised.
This only happens when using `babel:inherit` with the [babel-plugin-lodash](https://www.npmjs.com/package/babel-plugin-lodash).
It also only happens when using` import _ from 'lodash'`
If you do `const _ = required('lodash')` then it works

### Test Source

```js
//index.js
export const CONFIG1 = { foo: 'bar', foooo: 'baaaaar' }
```

```js
//index.js in test directory
import test from 'ava';
import _ from 'lodash';
import * as consts from '../index';

test('sample test', t => {
    t.true(_.isPlainObject(consts.CONFIG1));
})
```

### Error Message & Stack Trace

```
Uncaught Exception: test\index.js
  TypeError: C:/_DevRootGit/Demo/lodashtest/test/index.js: Cannot read property 'length' of undefined
    at hasSpread (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-plugin-transform-es2015-spread\lib\index.js:21:30)
    at PluginPass.CallExpression (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-plugin-transform-es2015-spread\lib\index.js:92:14)
    at newFn (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\visitors.js:276:21)
    at NodePath._call (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\path\context.js:48:17)
    at NodePath.visit (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\path\context.js:105:12)
    at TraversalContext.visitQueue (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitSingle (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\context.js:108:19)
    at TraversalContext.visit (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\context.js:192:19)
    at Function.traverse.node (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\path\context.js:115:19)
    at TraversalContext.visitQueue (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\context.js:150:16)
    at TraversalContext.visitMultiple (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\context.js:103:17)
    at TraversalContext.visit (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\context.js:190:19)
    at Function.traverse.node (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\index.js:114:17)
    at NodePath.visit (C:\_DevRootGit\Demo\lodashtest\node_modules\babel-traverse\lib\path\context.js:115:19)
From previous event:
    at Api._runWithPool (C:\_DevRootGit\Demo\lodashtest\node_modules\ava\api.js:243:5)
    at _setupPrecompiler.then.then (C:\_DevRootGit\Demo\lodashtest\node_modules\ava\api.js:174:17)

```

### Config

```json
{
  "ava": {
    "files": [
      "test/**/*.js"
    ],
    "concurrency": 5,
    "require": [
      "babel-register"
    ],
    "babel": "inherit"
  }
}
```

### Command-Line Arguments

```
cross-env NODE_ENV=test ava -v
```
## Environment

```
Ava : 0.22.0
Node : 6.10
NPM : 3.10
Windows 10
```

**Comment by kevva** [comment]
Looks like an issue with `babel-plugin-lodash`. This comment describes the same issue https://github.com/lodash/babel-plugin-lodash/issues/188#issuecomment-322873062.
