### ISSUE TITLE
TypeError: `string` and `indent` should be strings

### ISSUE THREAD

**Issue by OKNoah** [avajs/ava#1537]
## Description

With `ava@0.22.0` (but NOT `ava@0.21.0`), I get the error `TypeError: `string` and `indent` should be strings`. It does not seem to matter what the test is.

### Test Source

```js
import test from 'ava'

test('should render', (t) => {
  t.pass()
})
```

### Error Message & Stack Trace

```
./node_modules/.bin/ava src/components/mai-fields/TextField.test.js 
 
 ⠋ /Users/my-user/Projects/my-project/node_modules/ava/lib/cli.js:205
          throw err;
          ^

TypeError: `string` and `indent` should be strings
    at module.exports (/Users/my-user/Projects/my-project/node_modules/indent-string/index.js:6:9)
    at unflattened.reduceRight (/Users/my-user/Projects/my-project/node_modules/hullabaloo-config-manager/lib/codegen.js:31:70)
    at Array.reduceRight (native)
    at generateFactory (/Users/my-user/Projects/my-project/node_modules/hullabaloo-config-manager/lib/codegen.js:24:37)
    at codegen (/Users/my-user/Projects/my-project/node_modules/hullabaloo-config-manager/lib/codegen.js:46:39)
    at ResolvedConfig.generateModule (/Users/my-user/Projects/my-project/node_modules/hullabaloo-config-manager/lib/ResolvedConfig.js:32:12)
    at configManager.fromConfig.then.result (/Users/my-user/Projects/my-project/node_modules/ava/lib/babel-config.js:74:41)
    at <anonymous>
From previous event:
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)
From previous event:
    at Api.run (/Users/my-user/Projects/my-project/node_modules/ava/api.js:76:5)
    at Object.exports.run (/Users/my-user/Projects/my-project/node_modules/ava/lib/cli.js:196:7)
    at Object.<anonymous> (/Users/my-user/Projects/my-project/node_modules/ava/cli.js:15:24)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
```

### Config

At first I did not use any config, I added config based on https://github.com/mikenikles/enzyme-example-ava

```json
{
  "ava": {
    "babel": "inherit",
    "require": "./test-setup.js"
  }
}
```

### Command-Line Arguments

Tried all of the below

```
ava
./node_modules/.bin/ava
./node_modules/.bin/ava **/*.test.js
./node_modules/.bin/ava exact/path/to/test/file.js
```

## Relevant Links

Used as examples for setting up:
https://github.com/kamataryo/enzyme-example-ava
http://airbnb.io/enzyme/docs/guides/tape-ava.html
Project long ago forked from:
https://github.com/erikras/react-redux-universal-hot-example

## Environment

```
Node.js v8.1.0
darwin 17.0.0
ava 0.22.0
npm 5.0.3
```

**Comment by sindresorhus** [comment]
Upgrade npm. Older 5.x versions are super buggy and install incorrect sub-dependencies.

**Comment by novemberborn** [comment]
Also when things get weird, try `npm rm ava` followed by `npm install --save-dev ava`. That should force sub-dependencies to be updated.
