### ISSUE TITLE
Stack trace / source map issues

### ISSUE THREAD

**Issue by niftylettuce** [avajs/ava#1584]
I think this is due to using Babel.  If you're writing a pure JS function/class to write tests with Ava against, then the stack traces/source mapping is off.  For example, a bug occurs on 166 of my file `index.js`, however the stack trace output shows line 4.

```log
  TypeError: Cannot set property 'log' of undefined
      at Object.keys.forEach.key (/Users/user/Projects/cabin/index.js:4:666)
      at Array.forEach (<anonymous>)
      at Cabin.middleware (/Users/user/Projects/cabin/index.js:4:582)
      at dispatch (/Users/user/Projects/cabin/node_modules/koa-compose/index.js:42:32)
      at /Users/user/Projects/cabin/node_modules/koa-compose/index.js:34:12
      at Application.handleRequest (/Users/user/Projects/cabin/node_modules/koa/lib/application.js:150:12)
      at Server.handleRequest (/Users/user/Projects/cabin/node_modules/koa/lib/application.js:132:19)
      at emitTwo (events.js:126:13)
      at Server.emit (events.js:214:7)
      at parserOnIncoming (_http_server.js:602:12)
      at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
```

**Comment by novemberborn** [comment]
@niftylettuce is that `index.js` file the result of a Babel compilation in any way? And if so are you inlining the source map, or writing it to disk?

**Comment by niftylettuce** [comment]
No it is pure JavaScript/Node, no Babel compilation at all.

**Comment by novemberborn** [comment]
No accidental `babel-register` usage either? AVA shouldn't rewrite stack traces without a source map. The character offsets seem really high though (`666`, `582`) which implies some sort of transform.

**Comment by niftylettuce** [comment]
Not using babel anywhere in the project.  I am using `cross-env NODE_ENV=test nyc ava` to run tests, but I'm pretty sure this happened even with pure `ava`.

versions:
nyc 11.1.0
ava 0.22.0
cross-env 5.0.5

you can view source here:

https://github.com/cabinjs/cabin

**Comment by novemberborn** [comment]
Could you push a branch where the above error occurs?

**Comment by niftylettuce** [comment]
Related to #1805 as well, just experienced it again still.

**Comment by novemberborn** [comment]
Closing in favor of https://github.com/avajs/ava/issues/974#issuecomment-390478448.
