### ISSUE TITLE
bug: test.todo hang the process when I pass a cb function.

### ISSUE THREAD

**Issue by jgdev** [avajs/ava#1615]
## Description

For bug reports, please provide as much *relevant* info as possible.

I have a lot of tests in todo, when I pass a cb function to one of them, the process is hanging up even if I define a timeout when I include the package `mongo-in-memory`.

I'm not creating any instance of [mongo-in-memory](https://github.com/giorgio-zamparelli/mongo-in-memory), I just require that dependency, wich is only are exporting a [function](https://github.com/giorgio-zamparelli/mongo-in-memory/blob/master/index.js#L200), for the simple fact of that *ava* are no throwing the expected message: `'todo' tests are not allowed to have an implementation ...`

### Test Source

```js
import MongoInMemory from 'mongo-in-memory';
test.todo('bug - some test', t => {});
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
    "concurrency": 5,
    "failFast": true,
    "failWithoutAssertions": false,
    "powerAssert": false,
    "require": [
      "babel-register",
      "babel-polyfill"
    ],
    "babel": "inherit"
  }
}
```

### Command-Line Arguments

```
ava --timeout 10000 test/integration
```

## Environment

Node.js: v8.9.0
Platform: darwin 17.3.0
Ava: 0.24.0
Npm: 5.6.0

**Comment by novemberborn** [comment]
> I have a lot of tests in todo, when I pass a cb function to one of them, the process is hanging up even if I define a timeout when I include the package mongo-in-memory.

To clarify, the timeout indicates how long AVA should wait between tests completing until giving up. It's not a minimum amount of time for the test process to stay active.

> ava are no throwing the expected message: 'todo' tests are not allowed to have an implementation ...

Did you mean to say that `todo` tests with a callback are *not* printing the message?

If I run AVA with just `import test from 'ava'; test.todo(t => {})` I do get the message:

```
❯ npx ava -v

/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.uE4mJvK4L3/node_modules/ava/lib/runner.js:121
			throw new TypeError(validationError);
			^

TypeError: `todo` tests are not allowed to have an implementation. Use `test.skip()` for tests with an implementation.
    at Runner.addTest (/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.uE4mJvK4L3/node_modules/ava/lib/runner.js:121:10)
    at Function.Runner.chain.optionChain (/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.uE4mJvK4L3/node_modules/ava/lib/runner.js:101:10)
    at Function.wrappedFn (/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.uE4mJvK4L3/node_modules/option-chain/index.js:37:14)
    at Object.<anonymous> (/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.uE4mJvK4L3/test.js:3:6)
    at Module._compile (module.js:635:30)
    at extensions.(anonymous function) (/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.uE4mJvK4L3/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.uE4mJvK4L3/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/private/var/folders/2_/qczp184x76b2nl034sq5hvxw0000gn/T/tmp.uE4mJvK4L3/node_modules/ava/lib/test-worker.js:56:1)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
  ✖ test.js exited with a non-zero exit code: 1

  0 tests passed
  1 uncaught exception
```

It looks like we should improve this output though!

Once I add `import MongoInMemory from 'mongo-in-memory'` I just see:

```
❯ npx ava -v

  ✖ No tests found in test.js

  0 tests passed
  1 uncaught exception
```

I suspect this is an issue with its outdated https://github.com/winfinit/mongodb-prebuilt/ dependency, which has some side-effects. I can't reproduce this if I import the latest version instead.

**Comment by jgdev** [comment]
Just changed to `mongodb-memory-server` and it works for me.

**Comment by jgdev** [comment]
Just changed to mongodb-memory-server and it works for me.
