### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by PvPGodNotReally** [avajs/ava#1656]
(function (exports, require, module, __filename, __dirname) { module.exports.run => (client, message, args) {
                                                                    ^

SyntaxError: Unexpected token .
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)

**Comment by sindresorhus** [comment]
For support questions, use https://gitter.im/avajs/ava instead.
