### ISSUE TITLE
Ava doesn't allow built-in object-rest spread operator?

### ISSUE THREAD

**Issue by niftylettuce** [avajs/ava#1690]
I get `Unexpected token` errors when using object rest spread even though I'm on Node v8.9.0 in this particular project where I encounter this, and its built in http://node.green/#ES2018-features-object-rest-spread-properties.

**Comment by niftylettuce** [comment]
Note that this only happens when object rest spread is used in the test files.

**Comment by novemberborn** [comment]
@niftylettuce which AVA version are you using?

**Comment by friday** [comment]
It was introduced in 0.18 and happens in babel transpilation with Node.js older than v8.3. There might be more conditions involved but this is what I was able to narrow it down to.

I'm guessing it's just the babel presets that needs tweaking. AVA changed the babel conf at 0.18.

```
  Uncaught Exception
  SyntaxError: /Users/albin/src/eslint-plugin-lodash-fp/test/consistent-name.js: Unexpected token (58:8)
SyntaxError: /Users/albin/src/eslint-plugin-lodash-fp/test/consistent-name.js: Unexpected token (58:8)
  56 |       code: `var lodash = require('lodash');`,
  57 |       errors: [Object.assign({
> 58 |         ...error, message: 'Lodash should be imported as `_`'
     |         ^
  59 |       }, error)]
  60 |     }
  61 |   ]
    at Parser.pp$5.raise (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseIdentifier (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:4332:10)
    at Parser.pp$3.parsePropertyName (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:4156:96)
    at Parser.pp$3.parseObj (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:4045:12)
    at Parser.pp$3.parseExprAtom (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3719:19)
    at Parser.pp$3.parseExprSubscripts (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseExprListItem (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:4312:16)
    at Parser.pp$3.parseCallExpressionArguments (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3573:20)
    at Parser.pp$3.parseSubscripts (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3533:31)
    at Parser.pp$3.parseExprSubscripts (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3504:15)
    at Parser.pp$3.parseMaybeUnary (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/babylon/lib/index.js:3474:19)
From previous event:
    at Api._runWithoutPool (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/ava/api.js:234:5)
    at /Users/albin/src/eslint-plugin-lodash-fp/node_modules/ava/api.js:161:23
From previous event:
    at Api._run (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/ava/api.js:150:5)
    at /Users/albin/src/eslint-plugin-lodash-fp/node_modules/ava/api.js:75:24
From previous event:
    at Api.run (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/ava/api.js:75:5)
    at Object.exports.run.api.on.api.run.then [as run] (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/ava/lib/cli.js:165:7)
    at Object.<anonymous> (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/ava/cli.js:22:24)
    at Module._compile (module.js:409:26)
    at Module.replacementCompile (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at module.exports (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/nyc/node_modules/default-require-extensions/js.js:8:9)
    at Object.<anonymous> (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/nyc/node_modules/append-transform/index.js:62:4)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at runMain (/Users/albin/.node-spawn-wrap-62817-995987306568/node:68:10)
    at Function.<anonymous> (/Users/albin/.node-spawn-wrap-62817-995987306568/node:171:5)
    at Object.<anonymous> (/Users/albin/src/eslint-plugin-lodash-fp/node_modules/nyc/bin/wrap.js:23:4)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at /Users/albin/.node-spawn-wrap-62817-995987306568/node:178:8
```

**Comment by novemberborn** [comment]
This is fully supported in the 1.0 betas.

**Comment by rinu** [comment]
I'm using ava beta 8 and still getting that SyntaxError. I tried adding `babel-plugin-syntax-object-rest-spread` as well, still nothing.
I'm trying to add unit tests to a project that uses spread syntax all over the place. Apart from this limitation, ava is the first thing that actually works.

**Comment by novemberborn** [comment]
@rinu it sounds like you're using spread syntax in your source files? AVA [does not compile sources out of the box](https://github.com/avajs/ava/blob/master/docs/recipes/babel.md#compile-sources), so if you're running on a Node.js version that doesn't support this syntax then it won't work.

It does work in test files, because we do compile those.

**Comment by rinu** [comment]
I was following a badly out of date example project (https://github.com/eddyerburgh/vue-test-utils-ava-example) which I think does attempt to compile sources as well. Anyway, thanks @novemberborn for getting me on the right track!

**Comment by ToniChaz** [comment]
Hi @novemberborn I have tha same problem with ava@1.0.0-beta.8 and Node@10.3.0

![screen shot 2018-09-25 at 13 09 18](https://user-images.githubusercontent.com/3285048/46010861-637c1780-c0c4-11e8-9628-c3ac9ee3620a.png)
![screen shot 2018-09-25 at 13 06 28](https://user-images.githubusercontent.com/3285048/46010870-6a0a8f00-c0c4-11e8-8167-319b532bb873.png)

¿Any solution?

**Comment by novemberborn** [comment]
@ToniChaz given that the error is coming from `babylon` this seems to be a problem with your precompiler setup, not AVA.
