### ISSUE TITLE
Running cli with `todo` and `match` causes validation error message

### ISSUE THREAD

**Issue by yoiang** [avajs/ava#1731]
## Description

Running from the cli using a `match` parameter causes the following validation message to be displayed:

`todo` tests are just for documentation and cannot be used with `skip`, `only`, or `failing`

Removing the match parameter causes proper functionality.

### Test Source

```js
ava.todo('This is (not) a test')
```

### Error Message & Stack Trace

```
/Users/----/Documents/----/repo/node_modules/ava/lib/runner.js:121
			throw new TypeError(validationError);
			^

TypeError: `todo` tests are just for documentation and cannot be used with `skip`, `only`, or `failing`
    at Runner.addTest (/Users/----/Documents/----/repo/node_modules/ava/lib/runner.js:121:10)
    at Function.Runner.chain.optionChain (/Users/----/Documents/----/repo/node_modules/ava/lib/runner.js:101:10)
    at Function.wrappedFn (/Users/----/Documents/----/repo/node_modules/option-chain/index.js:37:14)
    at Object.<anonymous> (/Users/----/Documents/----/repo/test/Utility/Genetics/Gene/Number.js:17:6)
    at Module._compile (module.js:643:30)
    at extensions.(anonymous function) (/Users/----/Documents/----/repo/node_modules/require-precompiled/index.js:13:11)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/----/Documents/----/repo/node_modules/ava/lib/process-adapter.js:100:4)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/----/Documents/----/repo/node_modules/ava/lib/test-worker.js:62:1)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

### Config

```json
"ava": {
    "files": [
      "test/**/*.js"
    ],
    "sources": [
      "src/**/*.{js,jsx}",
      "!bundle/**/*"
    ],
    "require": [
      "babel-register"
    ]
  }
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava test --match '!*----*'
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v8.9.4
darwin 17.4.0
0.25.0
5.6.0
```

**Comment by novemberborn** [comment]
This should be fixed in the 1.0, which is currently in beta. Install using `npm i -D ava@next`.

Please let me know if this is still an issue after you upgrade though.
