### ISSUE TITLE
Error: watch package.json ENOSPC

### ISSUE THREAD

**Issue by sudo-suhas** [avajs/ava#1801]
## Description

I got an unexpected error when I tried to run `ava` in watch mode.

### Test Source

This happened to me when I was working on the [`listr`](https://github.com/SamVerschueren/listr) codebase. So the following should be enough to reproduce the error:

```
git clone git@github.com:SamVerschueren/listr.git
cd listr
yarn
./node_modules/.bin/ava --watch
```

### Error Message & Stack Trace

```
 ⠋ events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: watch package.json ENOSPC
    at _errnoException (util.js:1022:11)
    at FSWatcher.start (fs.js:1382:19)
    at Object.fs.watch (fs.js:1408:11)
    at createFsWatchInstance (/home/suhaskaranth/dev/oss/listr/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/home/suhaskaranth/dev/oss/listr/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/home/suhaskaranth/dev/oss/listr/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/home/suhaskaranth/dev/oss/listr/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/home/suhaskaranth/dev/oss/listr/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:153:5)
```

### Config

No special configuration, see https://github.com/SamVerschueren/listr/blob/master/package.json

### Command-Line Arguments

```
./node_modules/.bin/ava --watch
```

## Relevant Links

https://github.com/SamVerschueren/listr

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
➜ node -e "var os=require('os');console.log('Node.js ' + process.version + '\n' + os.platform() + ' ' + os.release())"
Node.js v8.11.1
linux 4.15.0-20-generic

➜ ./node_modules/.bin/ava --version
0.25.0

➜ npm --version
5.6.0
```

**Comment by sudo-suhas** [comment]
This issue does not occur on my system anymore. Did not do any changes. I already had updated the limit for maximum files that can be watched:
```
➜ tail -2 /etc/sysctl.conf  
fs.inotify.max_user_watches=524288
```
I will update here if I face the issue again.
