### ISSUE TITLE
profile.js script does not respect extension configuration

### ISSUE THREAD

**Issue by novemberborn** [avajs/ava#1819]
The `profile.js` script will apply the Babel configuration to whatever file it's called with, regardless of `extensions` configuration.

This shouldn't be too dreadful to fix, but we'd rather do #1505.

**Comment by goooseman** [comment]
I'm working with ava and typescript using following config:

```js
export default {
  compileEnhancements: false,
  extensions: ["ts"],
  files: ["test/**/*.ts", "src/**/*.spec.ts"],
  require: ["ts-node/register", "./test/helpers/enzyme.js", "./test/helpers/module-alias.js"],
};
```

And just launch ava from ava binary (`npx ava`) works great.
`npx ava test/app.spec.ts` - works ok.
But when I launch it through `profile.js`, it does not work:
`node node_modules/ava/profile.js test/app.spec.ts`
Outputs:
```
SyntaxError: /Users/goooseman/dev/myProjects/boodka-desktop/test/app.spec.ts: Unexpected token (6:18)
    at Parser.raise (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:3938:15)
    at Parser.unexpected (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:5247:16)
    at Parser.parseVar (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:7768:18)
    at Parser.parseVarStatement (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:7594:10)
    at Parser.parseStatementContent (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:7194:21)
    at Parser.parseStatement (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:7144:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:7695:23)
    at Parser.parseBlockBody (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:7682:10)
    at Parser.parseTopLevel (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:7109:10)
    at Parser.parse (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:8495:17)
    at parse (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/parser/lib/index.js:10448:38)
    at parser (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
    at normalizeFile (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
    at runSync (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/core/lib/transformation/index.js:44:43)
    at Object.transformSync (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/@babel/core/lib/transform.js:43:38)
    at filename (/Users/goooseman/dev/myProjects/boodka-desktop/node_modules/ava/lib/babel-pipeline.js:201:29)
```

**Comment by novemberborn** [comment]
@goooseman yes, that's what this issue is about. Would you be able to help us fix it?

Or, perhaps, implement a proper debug mode? https://github.com/avajs/ava/issues/1505

**Comment by goooseman** [comment]
@novemberborn wrote a little PR to fix that
