### ISSUE TITLE
Running tests with snapshots using profile.js throws exception

### ISSUE THREAD

**Issue by sharkykh** [avajs/ava#1909]
## Description

Running the following test normally using `ava test.js` works fine.
However, running the same file using `profile.js` (`node node_modules/ava/profile.js test.js`) produces an error.
I checked the code and the reason seems to be that `projectDir` is `undefined` here:
https://github.com/avajs/ava/blob/f7fce6a81cf8ee77d0e4823e4ff8961d5097da17/lib/runner.js#L172

### Test Source

```js
// test.js
import test from 'ava';

test('reproducible snapshot bug', t => {
    try {
        t.snapshot('foo');
    } catch (error) {
        console.error(error);
    }
});
```

### Error Message & Stack Trace

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.relative (path.js:499:5)
    at Runner.compareTestSnapshot (C:\Dev\ava-profile-snapshot-bug\node_modules\ava\lib\runner.js:172:19)
    at Test.compareWithSnapshot.assertionOptions [as compareWithSnapshot] (C:\Dev\ava-profile-snapshot-bug\node_modules\ava\lib\test.js:123:19)
    at Test.snapshot (C:\Dev\ava-profile-snapshot-bug\node_modules\ava\lib\assert.js:536:19)
    at snapshot (C:\Dev\ava-profile-snapshot-bug\test.js:5:11)
    at Test.callFn (C:\Dev\ava-profile-snapshot-bug\node_modules\ava\lib\test.js:313:21)
    at Test.run (C:\Dev\ava-profile-snapshot-bug\node_modules\ava\lib\test.js:326:23)
    at Runner.runSingle (C:\Dev\ava-profile-snapshot-bug\node_modules\ava\lib\runner.js:257:19)
    at runHooks.then.hooksOk (C:\Dev\ava-profile-snapshot-bug\node_modules\ava\lib\runner.js:317:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)

  × reproducible snapshot bug Test finished without running any assertions

  1 test failed

  reproducible snapshot bug


  Error: Test finished without running any assertions
```

### Config

Using default configuration

### Command-Line Arguments

```shell
node node_modules/ava/profile.js test.js
```

## Relevant Links

Minimal reproduction: https://github.com/sharkykh/ava-profile-snapshot-bug
Run `yarn profile` to reproduce the bug.
**Seems like there's another bug though**, so you may need to run `yarn test` first to populate the cache folder.

## Environment

**OS:** Windows 7 SP1 6.1.7601 x64
**Node.js:** 10.7.0
**yarn:** 1.9.4
**AVA:** 1.0.0-beta.7 (FWIW, bug is also present on version 0.25.0)

**Comment by novemberborn** [comment]
We probably need to add `projectDir` to the object here: https://github.com/avajs/ava/blob/7f974ccd1f2320eaf010db917f17b09922342b86/profile.js#L79:L87

There's a bunch of other problems with `profile.js`, see https://github.com/avajs/ava/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+profile. I'd like to see if AVA can work with https://github.com/GoogleChromeLabs/ndb.

**Comment by sharkykh** [comment]
> We probably need to add `projectDir` to the object here
I can confirm it fixes the issue.

**Comment by novemberborn** [comment]
> I can confirm it fixes the issue.

Would you like to submit a PR? It's hard to proactively maintain `profile.js` but we can definitely land bug fixes when we inevitably break it 😄
