### ISSUE TITLE
Update Babel to rc.2

### ISSUE THREAD

**Issue by gajus** [avajs/ava#1916]
## Problem

```
  TypeError: programPath.hub.addHelper is not a function
  TypeError: programPath.hub.addHelper is not a function
      at wrapInterop (/home/travis/build/gajus/roarr/node_modules/@babel/helper-module-transforms/lib/index.js:165:45)
      at PluginPass.exit (/home/travis/build/gajus/roarr/node_modules/@babel/plugin-transform-modules-commonjs/lib/index.js:174:70)
      at newFn (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/path/context.js:97:8)
      at TraversalContext.visitQueue (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/context.js:118:16)
      at TraversalContext.visitSingle (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/context.js:90:19)
      at TraversalContext.visit (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/context.js:146:19)
      at Function.traverse.node (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/index.js:94:17)
      at traverse (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/traverse/lib/index.js:76:12)
      at transformFile (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/core/lib/transformation/index.js:88:29)
      at runSync (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/core/lib/transformation/index.js:45:3)
      at Object.transformSync (/home/travis/build/gajus/roarr/node_modules/ava/node_modules/@babel/core/lib/transform.js:43:38)
      at Object.filename [as precompileFull] (/home/travis/build/gajus/roarr/node_modules/ava/lib/babel-pipeline.js:201:29)
      at map.reduce (/home/travis/build/gajus/roarr/node_modules/ava/api.js:161:28)
  From previous event:
      at emittedRun.then.then.precompilation (/home/travis/build/gajus/roarr/node_modules/ava/api.js:153:27)

```

https://travis-ci.org/gajus/roarr/jobs/419084579#L3317

## Fix

Update:

https://github.com/avajs/ava/blob/0ecd0be849b2cb1b01db8e0834827f4b411b3ea0/package.json#L64-L68

to version 7.0.0-rc.2.

## Context

Refer to:

https://github.com/babel/babel/issues/8508

**Comment by novemberborn** [comment]
For now I suggest you keep your plugin / preset dependencies pinned to rc1.

Babel 7 should be coming out [imminently](https://twitter.com/left_pad/status/1031700991186489344?s=21). I'll try and do another beta release this weekend where we change our dependencies to `^7.0.0`.

**Comment by gajus** [comment]
> Babel 7 should be coming out imminently. I'll try and do another beta release this weekend where we change our dependencies to ^7.0.0.

Babel stable release didn't happen and suggesting to hardcode a dependency version is not a good solution.

**Comment by novemberborn** [comment]
> suggesting to hardcode a dependency version is not a good solution.

It is when your dependencies are pre-releases.

Babel 7 release is now [likely to be Monday](https://github.com/babel/babel/issues/8508#issuecomment-416001814), so I'll try and follow up with an AVA beta after that.

**Comment by gajus** [comment]
@novemberborn Whats the release plan now that Babel v7 is out?
