### ISSUE TITLE
Common module dependency cause TypeError

### ISSUE THREAD

**Issue by lucaperret** [avajs/ava#1981]
## Description

Two module are using a method from the other one, it break only on AVA environment.

### Test Source

**src/a.ts**
```ts
import b from './b'
export default function a(): boolean {
  return typeof b() === 'boolean'
}
```
**src/b.ts**
```ts
import a from './a'

let bar: boolean
if (a()) {
  bar = true
}

export default function b(): boolean {
  return bar
}
```
**test/a.ts**
```ts
import test from 'ava'
import a from '../src/a'

test('foo', t => {
  t.true(a())
})

```
### Error Message & Stack Trace

```
Uncaught exception in test/a.ts

  /src/b.ts:4

   3: let bar: boolean
   4: if (a()) {
   5:   bar = true

  TypeError: a_1.default is not a function

  Object.<anonymous> (src/b.ts:4:6)
  Module.m._compile (node_modules/ts-node/src/index.ts:439:23)
  Object.require.extensions.(anonymous function) [as .ts] (node_modules/ts-node/src/index.ts:442:12)
```

### Config

`ava.config.js`

```js
export default {
  compileEnhancements: false,
  extensions: ['ts'],
  require: ['ts-node/register'],
  babel: false
}
```

### Command-Line Arguments

```
ava
```

## Relevant Links

- Complete repository: https://github.com/lucaperret/ava-ts-test-fails
- Maybe the same as #1952

## Environment

```
Node.js v11.1.0
darwin 17.7.0
ava 1.0.0-rc.2
npm 6.4.1
```

**Comment by havenchyk** [comment]
@lucaperret I just tried your example with circular dependencies and you know, after `tsc` node also complains about the same, so it's not a problem of ava.

**Comment by havenchyk** [comment]
@lucaperret maybe you could also provide your tsconfig?

**Comment by lucaperret** [comment]
Hi @havenchyk 
Here's the `tsconfig.json`
```json
{
  "compilerOptions": {
    "target": "esnext",
    "module": "commonjs",
    "sourceMap": true,
    "outDir": "dist",
    "declarationDir": "dist/types",
    "declaration": true,
    "esModuleInterop": true,
    "strict": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "noImplicitAny": true
  },
  "include": ["src/**/*"],
  "exclude": ["node_modules", "dist"]
}
```

**Comment by havenchyk** [comment]
@lucaperret so, I created a new project, put there a.ts, b.ts and index.ts, index.ts looks like 

```
import a from './a'

console.log(a())
```

then I run `tsc` with your config and got 

```
"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const a_1 = __importDefault(require("./a"));
console.log(a_1.default());
//# sourceMappingURL=index.js.map
```
for index.js. I tried to run `node dist/index.js` and received this error

```
if (a_1.default()) {
               ^

TypeError: a_1.default is not a function
    at Object.<anonymous> (/Users/havenchyk/projects/typeorm-test-docker/dist/b.js:8:16)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/havenchyk/projects/typeorm-test-docker/dist/a.js:6:29)
    at Module._compile (module.js:653:30)
```

**Comment by lucaperret** [comment]
It happen on AVA, but not on building with `tsc`.
Here's the repository: https://github.com/lucaperret/ava-ts-test-fails

**Comment by havenchyk** [comment]
Thanks for the repo. @lucaperret, how to make sure it works? I do `npm i`, `npm run build`, `node ./dist/index.js` -> 


```
ava-ts-test-fails/dist/b.js:8

if (a_1.default()) {
               ^

TypeError: a_1.default is not a function
```

and after `npx ts-node ./src/index.ts ` I got `a_1.default is not a function`

What're your results?

**Comment by lucaperret** [comment]
Also have this issue when running with node...

**Comment by havenchyk** [comment]
@lucaperret I think that the problem is with typescript that doesn't handle circular dependencies well.

**Comment by lucaperret** [comment]
Thanks for your help @havenchyk, I'll fix that by creating a module who exports both method.
