### ISSUE TITLE
Nyc breaking ava?

### ISSUE THREAD

**Issue by OmgImAlexis** [avajs/ava#2031]
## Description
I'm hoping someone here can point me to where this issue may be coming from. It seems `nyc` is having an issue with my code but even weirder is that after running `nyc` `ava` no longer runs properly.

I did find if I did a `git reset --hard` which shouldn't affect anything fixed `ava`?

I've also tried this with `nyc@12.0.2` and `nyc@13.1.0` with the same results.

### Error Message & Stack Trace

<details>
	<summary>Click to open</summary>

```console
root@Devon:/mnt/disks/code/api# yarn ava --verbose
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose

  ✔ disks › get-disks › should return no disks
  ✔ shares › get-shares › should return no shares
  ✔ disks › id › get-disk › should return 404 when no disk found
  ✔ disks › id › get-disk › should return disk based on id
  ✔ users › get-users › should return root user
  ✔ vars › get-vars › should return all vars
  ✔ vms › get-vms › should return no vms
  ✔ info › get-info › should return all info (libvirt enabled) (4.5s)

  7 tests passed
  1 known failure

  vms › get-vms › should return no vms

Done in 12.68s.
root@Devon:/mnt/disks/code/api# yarn ava --verbose
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose

  ✔ disks › get-disks › should return no disks
  ✔ disks › id › get-disk › should return 404 when no disk found
  ✔ disks › id › get-disk › should return disk based on id
  ✔ shares › get-shares › should return no shares
  ✔ users › get-users › should return root user
  ✔ vars › get-vars › should return all vars
  ✔ vms › get-vms › should return no vms
  ✔ info › get-info › should return all info (libvirt enabled) (4.5s)

  7 tests passed
  1 known failure

  vms › get-vms › should return no vms

Done in 12.70s.
root@Devon:/mnt/disks/code/api# yarn nyc ava --verbose
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/nyc ava --verbose

  ✔ disks › get-disks › should return no disks
  ✔ disks › id › get-disk › should return 404 when no disk found
  ✔ disks › id › get-disk › should return disk based on id
  ✔ shares › get-shares › should return no shares
  ✔ vars › get-vars › should return all vars
  ✔ users › get-users › should return root user

  Uncaught exception in test/specs/routes/api/v1/info/get-info.spec.js

  /mnt/disks/code/api/app/states/index.js:45

   44:   states = newStates;
   45:   logger.debug('States updated', newStates);
   46:

  TypeError: Cannot read property 'debug' of undefined

  getStates (app/states/index.js:45:9)
  Object.<anonymous> (app/operations-manager.js:13:46)

  ✖ test/specs/routes/api/v1/info/get-info.spec.js exited with a non-zero exit code: 1

  Uncaught exception in test/specs/routes/api/v1/vms/get-vms.spec.js

  /mnt/disks/code/api/app/states/index.js:45

   44:   states = newStates;
   45:   logger.debug('States updated', newStates);
   46:

  TypeError: Cannot read property 'debug' of undefined

  getStates (app/states/index.js:45:9)
  Object.<anonymous> (app/operations-manager.js:13:46)

  ✖ test/specs/routes/api/v1/vms/get-vms.spec.js exited with a non-zero exit code: 1

  6 tests passed
  2 uncaught exceptions

----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@Devon:/mnt/disks/code/api# yarn ava --verbose
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose

  Uncaught exception in test/specs/routes/api/v1/disks/get-disks.spec.js

  /mnt/disks/code/api/test/specs/routes/api/v1/disks/get-disks.spec.js:8

   7:   // Empty request
   8:   const request = {};
   9:   const req = mockReq(request);

  TypeError: Cannot read property 'beforeEach' of undefined

  ✖ test/specs/routes/api/v1/disks/get-disks.spec.js exited with a non-zero exit code: 1

  Uncaught exception in test/specs/routes/api/v1/shares/get-shares.spec.js

  /mnt/disks/code/api/test/specs/routes/api/v1/shares/get-shares.spec.js:8

   7:   // Empty request
   8:   const request = {};
   9:   const req = mockReq(request);

  TypeError: Cannot read property 'beforeEach' of undefined

  Uncaught exception in test/specs/routes/api/v1/disks/id/get-disk.spec.js

  /mnt/disks/code/api/test/specs/routes/api/v1/disks/id/get-disk.spec.js:8

   7:   // Empty request
   8:   const request = {};
   9:   const req = mockReq(request);

  TypeError: Cannot read property 'beforeEach' of undefined

  ✖ test/specs/routes/api/v1/shares/get-shares.spec.js exited with a non-zero exit code: 1

  Uncaught exception in test/specs/routes/api/v1/vars/get-vars.spec.js

  /mnt/disks/code/api/test/specs/routes/api/v1/vars/get-vars.spec.js:9

   8:   // Empty request
   9:   const request = {};
   10:   const req = mockReq(request);

  TypeError: Cannot read property 'beforeEach' of undefined

  Uncaught exception in test/specs/routes/api/v1/users/get-users.spec.js

  /mnt/disks/code/api/test/specs/routes/api/v1/users/get-users.spec.js:8

   7: test.beforeEach(t => {
   8:   // Empty request
   9:   const request = {};

  TypeError: Cannot read property 'beforeEach' of undefined

  ✖ test/specs/routes/api/v1/disks/id/get-disk.spec.js exited with a non-zero exit code: 1
  ✖ test/specs/routes/api/v1/vars/get-vars.spec.js exited with a non-zero exit code: 1
  ✖ test/specs/routes/api/v1/users/get-users.spec.js exited with a non-zero exit code: 1

  Uncaught exception in test/specs/routes/api/v1/info/get-info.spec.js

  /mnt/disks/code/api/test/specs/routes/api/v1/info/get-info.spec.js:111

   110: test.beforeEach(t => {
   111:   // Empty request
   112:   const request = {};

  TypeError: Cannot read property 'beforeEach' of undefined

  Uncaught exception in test/specs/routes/api/v1/vms/get-vms.spec.js

  /mnt/disks/code/api/test/specs/routes/api/v1/vms/get-vms.spec.js:8

   7:   // Empty request
   8:   const request = {};
   9:   const req = mockReq(request);

  TypeError: Cannot read property 'beforeEach' of undefined

  ✖ test/specs/routes/api/v1/info/get-info.spec.js exited with a non-zero exit code: 1
  ✖ test/specs/routes/api/v1/vms/get-vms.spec.js exited with a non-zero exit code: 1

  7 uncaught exceptions

error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@Devon:/mnt/disks/code/api# git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean
root@Devon:/mnt/disks/code/api# git reset --hard
HEAD is now at e42ba6f console -> logger
root@Devon:/mnt/disks/code/api# yarn ava --verbose
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose

  ✔ disks › get-disks › should return no disks
  ✔ shares › get-shares › should return no shares
  ✔ disks › id › get-disk › should return 404 when no disk found
  ✔ disks › id › get-disk › should return disk based on id
  ✔ users › get-users › should return root user
  ✔ vars › get-vars › should return all vars
  ✔ vms › get-vms › should return no vms
  ✔ info › get-info › should return all info (libvirt enabled) (4.7s)

  7 tests passed
  1 known failure

  vms › get-vms › should return no vms

Done in 14.09s.
```
</details>

### Config

Copy the relevant section from `package.json`:

```json
{
 "ava": {
  "require": [
   "esm"
  ],
  "sources": [
   "./index.js",
   "./app/**/*.js"
  ],
  "files": [
   "test/specs/**/*.spec.js"
  ],
  "rules": {
   "ava/no-todo-test": "off"
  },
  "babel": false
 },
 "nyc": {
  "require": [
   "esm"
  ]
 }
}
```

## Environment

```
Node.js v10.13.0
linux 4.19.16-unRAID
ava v1.2.0
npm v6.4.1
```

**Comment by novemberborn** [comment]
I think it might be caused by the combination of `nyc` and `esm`. It works great if those tools aren't using cached transforms (like in CI) but can fail locally if you run concurrent test files. Try with the `-c 1` option.

> I did find if I did a `git reset --hard` which shouldn't affect anything fixed `ava`?

AVA, `nyc` and `esm` cache files in `node_modules/.cache`. Try deleting that directory instead.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by OmgImAlexis** [comment]
No worries with closing the issue. Thanks for all the help.

Any other ideas on where to look and is the `Illegal invocation` error a bug?


```console
root@Devon:/mnt/disks/code/api# yarn ava --verbose -c 1
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose -c 1

  ✔ disks › get-disks › should return no disks
  ✔ vms › get-vms › should return no vms
  ✔ vars › get-vars › should return all vars
  ✔ users › get-users › should return root user
  ✔ shares › get-shares › should return no shares
  ✔ info › get-info › should return all info (libvirt enabled) (3s)
  ✔ disks › id › get-disk › should return 404 when no disk found
  ✔ disks › id › get-disk › should return disk based on id

  7 tests passed
  1 known failure

  vms › get-vms › should return no vms

Done in 31.47s.
root@Devon:/mnt/disks/code/api# yarn nyc ava --verbose -c 1
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/nyc ava --verbose -c 1
/mnt/disks/code/api/node_modules/clean-stack/index.js:1
TypeError: Illegal invocation
    at Object.<anonymous> (/mnt/disks/code/api/node_modules/clean-stack/index.js:6:20)
    at Generator.next (<anonymous>)
    at Object.replacementCompile (/mnt/disks/code/api/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (module.js:584:10)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@Devon:/mnt/disks/code/api# yarn ava --reset-cache
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --reset-cache

✔ Removed AVA cache files in /mnt/disks/code/api/node_modules/.cache/ava
Done in 1.28s.
root@Devon:/mnt/disks/code/api# yarn ava --verbose
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose

  ✔ disks › get-disks › should return no disks
  ✔ disks › id › get-disk › should return 404 when no disk found
  ✔ disks › id › get-disk › should return disk based on id
  ✔ shares › get-shares › should return no shares
  ✔ vars › get-vars › should return all vars
  ✔ users › get-users › should return root user
  ✔ vms › get-vms › should return no vms
  ✔ info › get-info › should return all info (libvirt enabled) (3.1s)

  7 tests passed
  1 known failure

  vms › get-vms › should return no vms

Done in 13.31s.
root@Devon:/mnt/disks/code/api# yarn ava --verbose
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose

  ✔ disks › get-disks › should return no disks
  ✔ shares › get-shares › should return no shares
  ✔ vars › get-vars › should return all vars
  ✔ disks › id › get-disk › should return 404 when no disk found
  ✔ disks › id › get-disk › should return disk based on id
  ✔ users › get-users › should return root user
  ✔ vms › get-vms › should return no vms
  ✔ info › get-info › should return all info (libvirt enabled) (3s)

  7 tests passed
  1 known failure

  vms › get-vms › should return no vms

Done in 10.63s.
root@Devon:/mnt/disks/code/api# yarn ava --verbose -c
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose -c

✖ The --concurrency or -c flag must be provided with a nonnegative integer.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
root@Devon:/mnt/disks/code/api# yarn ava --verbose -c 1
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/ava --verbose -c 1

  ✔ disks › get-disks › should return no disks
  ✔ vms › get-vms › should return no vms
  ✔ vars › get-vars › should return all vars
  ✔ users › get-users › should return root user
  ✔ shares › get-shares › should return no shares
  ✔ info › get-info › should return all info (libvirt enabled) (3s)
  ✔ disks › id › get-disk › should return 404 when no disk found
  ✔ disks › id › get-disk › should return disk based on id

  7 tests passed
  1 known failure

  vms › get-vms › should return no vms

Done in 27.25s.
root@Devon:/mnt/disks/code/api# yarn nyc ava --verbose -c 1
yarn run v1.13.0
$ /mnt/disks/code/api/node_modules/.bin/nyc ava --verbose -c 1
/mnt/disks/code/api/node_modules/clean-stack/index.js:1
TypeError: Illegal invocation
    at Object.<anonymous> (/mnt/disks/code/api/node_modules/clean-stack/index.js:6:20)
    at Generator.next (<anonymous>)
    at Object.replacementCompile (/mnt/disks/code/api/node_modules/nyc/node_modules/append-transform/index.js:58:13)
    at Module._extensions..js (module.js:584:10)
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |        0 |        0 |        0 |        0 |                   |
----------|----------|----------|----------|----------|-------------------|
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by OmgImAlexis** [comment]
@jdalton, sorry to bother but any chance you could look at this and give some guidance on where the issue may be coming from?
