### ISSUE TITLE
Error: spawn E2BIG when running AVA on many test files

### ISSUE THREAD

**Issue by bongofury** [avajs/ava#2032]
## Description
I use to run tests inside a monorepo with AVA, each module has its own tests.
After upgrading from version _0.22.0_ to _1.2.0_ , I receive the error **spawn E2BIG**.

The error occurs if I run AVA on all monorepo test files.
If I run AVA on single modules this does not occurs.

### Error Message & Stack Trace

```
  ✖ Internal error
  Error: spawn E2BIG
  Error: spawn E2BIG
      at _errnoException (util.js:1024:11)
      at ChildProcess.spawn (internal/child_process.js:323:11)
      at exports.spawn (child_process.js:502:9)
      at Object.exports.fork (child_process.js:103:10)
      at module.exports (/Users/ebianchi/facility/repos/fl-frontend-monorepo/node_modules/ava/lib/fork.js:55:34)
      at _computeForkExecArgv.then.execArgv (/Users/ebianchi/facility/repos/fl-frontend-monorepo/node_modules/ava/api.js:232:24)
      at <anonymous>
  From previous event:
      at runCallback (timers.js:789:20)
      at tryOnImmediate (timers.js:751:5)
      at processImmediate [as _immediateCallback] (timers.js:722:5)
  From previous event:
      at emittedRun.then.then.then.precompilation (/Users/ebianchi/facility/repos/fl-frontend-monorepo/node_modules/ava/api.js:208:23)
      at <anonymous>
      at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "ava": {
       "require": [
             "./runtime-helpers"
        ]
  }
}
```

### Command-Line Arguments

```
npx ava modules/*/test/**/*-spec.js
```

## Environment

```
Node.js v8.9.1
darwin 16.7.0
ava 1.2.0
npm 5.5.1
```

**Comment by novemberborn** [comment]
Oh fascinating!

We're passing options to the worker processes as a command line argument. I think it ends up being too large. The line is here: https://github.com/avajs/ava/blob/010914b9e5232312d2b611695776919084a65717/api.js#L232

This includes all precompiled files which in your case may be quite a lot. There may be other unnecessary data as well. I'll have a think about how else we can share these options.

**Comment by novemberborn** [comment]
@bongofury could you give #2035 a try? `npm install --save-dev avajs/ava#config-over-ipc`.

**Comment by bongofury** [comment]
As stated in the PR, it seems to be ok, thank you!

**Comment by novemberborn** [comment]
@bongofury great. This is out now in v1.2.1.
