### ISSUE TITLE
Error: You gave us a visitor for the node type TSImportType but it's not a valid type

### ISSUE THREAD

**Issue by mesqueeb** [avajs/ava#2047]
## Description

Testing broke after updating ava from 1.0.0-beta3 to 1.2.1.

### Test Source

Package: https://github.com/mesqueeb/filter-anything

### Error Message & Stack Trace

```
✖ Internal error
  Error: You gave us a visitor for the node type TSImportType but it's not a valid type
  Error: You gave us a visitor for the node type TSImportType but it's not a valid type
      at verify (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/visitors.js:130:13)
      at Object.explode (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/visitors.js:52:3)
      at traverse (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/index.js:75:12)
      at NodePath.traverse (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/path/index.js:161:24)
      at PluginPass.Program (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/babel-plugin-espower/lib/create-espower-visitor.js:28:22)
      at newFn (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/visitors.js:193:21)
      at NodePath._call (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/path/context.js:53:20)
      at NodePath.call (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/path/context.js:40:17)
      at NodePath.visit (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/path/context.js:88:12)
      at TraversalContext.visitQueue (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/context.js:118:16)
      at TraversalContext.visitSingle (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/context.js:90:19)
      at TraversalContext.visit (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/context.js:146:19)
      at Function.traverse.node (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/index.js:94:17)
      at traverse (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/traverse/lib/index.js:76:12)
      at transformFile (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/core/lib/transformation/index.js:88:29)
      at runSync (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/@babel/core/lib/transformation/index.js:45:3)
  From previous event:
      at emittedRun.then.then.precompilation (/Users/lucaban/.ghq/github.com/mesqueeb/filter-anything/node_modules/ava/api.js:174:27)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! filter-anything@1.1.1 test: `ava test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the filter-anything@1.1.1 test script.
```

### Config

Copy the relevant section from `package.json`:

```json
{
  "devDependencies": {
    "@ava/babel-preset-stage-4": "^2.0.0",
    "@babel/plugin-proposal-object-rest-spread": "^7.3.2",
    "@babel/preset-env": "^7.3.1",
    "ava": "^1.2.1",
    "rollup": "^0.67.4",
    "rollup-plugin-typescript2": "^0.19.2",
    "typescript": "^3.3.3333"
  },
  "ava": {
  ... // I have no ava property in package.json
  }
}
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
ava test
```

## Relevant Links

Public repo: https://github.com/mesqueeb/filter-anything

## Environment

Node.js v11.9.0
darwin 18.2.0
ava 1.2.1
npm 6.5.0

**Comment by ianwalter** [comment]
I have the same issue. Build failure can be found here: https://github.com/ianwalter/vue-component-reset/pull/3/checks?check_run_id=67824620

**Comment by oldj** [comment]
I had the same issue, then I executed the `npm update` command and everything worked fine.

**Comment by mesqueeb** [comment]
I tried `npm update` but still have the same error.

**Comment by novemberborn** [comment]
Hi @mesqueeb, I can reproduce this on your repo, but I don't understand where the error is coming from. However if I remove the `package-lock.json` and `node_modules`, then run `npm install` again, the problem goes away. I think there's a faulty or outdated dependency somewhere in your package lock.

P.S. You don't need to manually install `@ava/babel-preset-stage-4` and `@babel/plugin-proposal-object-rest-spread`. And `@babel/preset-env` doesn't seem to be used.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by mesqueeb** [comment]
@novemberborn 
thanks.

1. I removed these from package.json:
- `@ava/babel-preset-stage-4`
- `@babel/plugin-proposal-object-rest-spread`
- `@babel/preset-env`

2. and then deleted `node_modules` **and** `package-lock.json`

3. then reinstalled everything with `npm i`

and it works again 🎉
