### ISSUE TITLE
Couldn't find any files to test

### ISSUE THREAD

**Issue by liangzeng** [avajs/ava#2162]
```
ava 2.1.0
Node.js v10.15.1
osx darwin 17.7.0
npm v6.4.1
```

~root/test.js
```js
import test from 'ava';

test('foo', t => {
	t.pass();
});
```

command
```
npx ava test.js
```

terminal result:
![image](https://user-images.githubusercontent.com/8503065/59569899-92a73e80-90c2-11e9-988f-da5f837f593b.png)

**Comment by novemberborn** [comment]
As of the 2.0 release, if you're passing file arguments to the `ava` command they must be the paths to the test files, not glob patterns or directories. I'm not sure where `~root/rest.js` lives but perhaps it's not `test.js`?

Try running `npx ava` instead.

(I'm closing this issue for housekeeping purposes, but let's keep the conversation going.)

**Comment by szmarczak** [comment]
https://travis-ci.org/sindresorhus/got/jobs/650790224 (AVA 3.3.0)

```
  ✖ Couldn't find any files to test
  ✖ Internal error
  TypeError: Cannot read property 'length' of undefined
  TypeError: Cannot read property 'length' of undefined
      at Object.getPatternParts (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/utils/pattern.js:94:20)
      at PartialMatcher._getPatternSegments (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/providers/matchers/matcher.js:30:37)
      at PartialMatcher._fillStorage (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/providers/matchers/matcher.js:19:35)
      at new Matcher (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/providers/matchers/matcher.js:10:14)
      at new PartialMatcher (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/providers/matchers/partial.js:4:1)
      at DeepFilter._getMatcher (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/providers/filters/deep.js:16:16)
      at DeepFilter.getFilter (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/providers/filters/deep.js:11:30)
      at ProviderAsync._getReaderOptions (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/providers/provider.js:25:41)
      at ProviderAsync.read (/home/travis/build/sindresorhus/got/node_modules/ava/node_modules/fast-glob/out/providers/async.js:12:30)
      at Array.map (<anonymous>)
```

TS compiled successfully, but for some reason AVA failed.\
I think restarting the Travis job would fix it.
