### ISSUE TITLE
Internal errors should always be verbose

### ISSUE THREAD

**Issue by sindresorhus** [avajs/ava#2171]
## Description

I upgraded AVA in a project from v1 to v2 and got this error:

```
❯ ava

  ✖ Couldn't find any files to test

  ✖ Internal error
```

Which is not very useful.

Then I tried verbose mode and got:

```
❯ ava --verbose

  ✖ Couldn't find any files to test

  ✖ Internal error
  SyntaxError: /Users/sindresorhus/dev/oss/generator-nm/app/templates/test.js: Unexpected token, expected "{" (2:7)

    1 | import test from 'ava';
  > 2 | import <%= camelModuleName %> from '.';
      |        ^
    3 |
    4 | test('title', t => {
    5 | 	t.throws(() => {
  SyntaxError: /Users/sindresorhus/dev/oss/generator-nm/app/templates/test.js: Unexpected token, expected "{" (2:7)

    1 | import test from 'ava';
  > 2 | import <%= camelModuleName %> from '.';
      |        ^
    3 |
    4 | test('title', t => {
    5 | 	t.throws(() => {
      at Parser.raise (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:6344:17)
      at Parser.unexpected (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:7659:16)
      at Parser.expect (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:7645:28)
      at Parser.parseNamedImportSpecifiers (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:11177:10)
      at Parser.parseImport (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:11130:39)
      at Parser.parseStatementContent (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:9886:27)
      at Parser.parseStatement (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:9788:17)
      at Parser.parseBlockOrModuleBlockBody (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:10364:25)
      at Parser.parseBlockBody (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:10351:10)
      at Parser.parseTopLevel (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:9717:10)
      at Parser.parse (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:11233:17)
      at parse (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/parser/lib/index.js:11269:38)
      at parser (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/core/lib/transformation/normalize-file.js:170:34)
      at normalizeFile (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/core/lib/transformation/normalize-file.js:138:11)
      at runSync (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/core/lib/transformation/index.js:44:43)
      at Object.transformSync (/Users/sindresorhus/dev/oss/generator-nm/node_modules/@babel/core/lib/transform.js:43:38)
```

My mistake is that the testing patterns got looser.

However:
1. Errors should always be verbose, not just with `--verbose`.
2. The message `Couldn't find any files to test` is not really correct. It could find test files, it's just that one of them had a syntax error.

### Error Message & Stack Trace

```
❯ ava

  ✖ Couldn't find any files to test

  ✖ Internal error
```

### Config

None

### Command-Line Arguments

```
ava
```

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v10.16.0
darwin 18.6.0
AVA 2.1.0
npm 6.9.0
```

**Comment by novemberborn** [comment]
Both due to the age of this issue, and the state of our reporters, I've decided to roll this into #2501.
