### ISSUE TITLE
Can't debug on windows with vscode

### ISSUE THREAD

**Issue by Osmil** [avajs/ava#2241]
## Description

Debugging immediately fails with
```
TypeError: require(...).getRunner is not a function
```

```json
{
  "version": "0.2.0",
  "configurations": [
    {
      "type": "node",
      "request": "launch",
      "name": "Run AVA Current File",
      "program": "${workspaceFolder}/src/node_modules/ava/profile.js",
      "cwd": "${workspaceFolder}/src/packages/lca",
      "internalConsoleOptions": "neverOpen",
      "autoAttachChildProcesses": true,
      "outputCapture": "std",
      "env": {
        "NODE_ENV": "test"
      },
      "args": ["${file}"],
      "skipFiles": ["<node_internals>/**/*.js"]
    }
  ]
}
```

### Test Source

```js
test.serial('Should...', async t => {
const a = 1;
});

```

### Error Message & Stack Trace

```
Exception has occurred: TypeError
TypeError: require(...).getRunner is not a function
    at Object.<anonymous> (c:\Users\denni\test-web\src\node_modules\ava\lib\worker\main.js:2:40)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at extensions.(anonymous function) (C:\Users\denni\test-web\src\node_modules\require-precompiled\index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\denni\test-web\src\node_modules\ava\lib\worker\dependency-tracker.js:42:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (c:\Users\denni\test-web\src\node_modules\ava\index.js:7:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at extensions.(anonymous function) (C:\Users\denni\test-web\src\node_modules\require-precompiled\index.js:16:3)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\denni\test-web\src\node_modules\ava\lib\worker\dependency-tracker.js:42:4)
    at Module.load (internal/modules/cjs/loader.js:653:32)
```

### Config

Copy the relevant section from `package.json`:

```json
export default {
  cache: true,
  concurrency: 5,
  failFast: true,
  failWithoutAssertions: false,
  tap: true,
  verbose: true,
  compileEnhancements: false,
  babel: false,
  environmentVariables: {
    NODE_ICU_DATA: '../../node_modules/full-icu'
  },
  sources: ['server/**/*']
};
```

### Command-Line Arguments

Copy your npm build scripts or the `ava` command used:

```
cd 'C:\Users\denni\test-web/src/packages/lca'; ${env:NODE_ENV}='test'; & 'C:\Program Files\nodejs\node.exe' '--inspect-brk=22640' '..\..\node_modules\ava\profile.js' 'c:\Users\denni\test-web\src\packages\lca\server\test\digest-auth.spec.int.js'
```

## Relevant Links

- If your project is public, link to the repo so we can investigate directly.
- **BONUS POINTS:** Create a [minimal reproduction](http://stackoverflow.com/help/mcve) and upload it to GitHub. This will get you the fastest support.

## Environment

Tell us which operating system you are using, as well as which versions of Node.js, npm, and AVA. Run the following to get it quickly:

```
Node.js v10.16.3
win32 10.0.17763
ava --version
2.3.0
npm --version
6.9.0
```

**Comment by novemberborn** [comment]
I must admit I don't debug using `profile.js`, nor VSCode. So if anybody is able to reproduce this and figure out why the process isn't being initialized correctly that'd be grand.

**Comment by StarpTech** [comment]
@novemberborn How do you debug?

**Comment by novemberborn** [comment]
AVA now has a debug mode which resolve this issue.
