### ISSUE TITLE
3.7.1 does not work

### ISSUE THREAD

**Issue by PlkMarudny** [avajs/ava#2466]
Please provide details about:

* What you're trying to do

Set up a simplest possible test, following the documentation

* What happened

When running a test, getting a crash:

```
(node:10248) UnhandledPromiseRejectionWarning: C:\Users\Tomasz\Documents\js\ava\node_modules\ava\lib\node-arguments.js:9
                } catch {
                        ^

SyntaxError: Unexpected token {
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.exports.run (C:\Users\Tomasz\Documents\js\ava\node_modules\ava\lib\cli.js:267:33)
(node:10248) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10248) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
```

* What you expected to happen

Please share relevant sample code. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

We'll also need your AVA configuration (in `package.json` or `ava.config.*` configuration files) and how you're invoking AVA. Share the installed AVA version (get it by running `npx ava --version`).

```
{
  "name": "costam",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "ava"
  },
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "ava": "^3.7.1"
  }
}
```

ava 3.7.1

**Comment by novemberborn** [comment]
What Node.js version are you using?

**Comment by PlkMarudny** [comment]
8.11.1

**Comment by novemberborn** [comment]
AVA 3 requires 10.18.

Node.js 8 isn’t even maintained by Node.js anymore. You should migrate away from it.

**Comment by PlkMarudny** [comment]
OK, thank  you.
