### ISSUE TITLE
Crashes with Node 14

### ISSUE THREAD

**Issue by ehmicky** [avajs/ava#2472]
Ava crashes when used with Node 14.

`test.js`:

```js
require('ava')
```

Command line:

```bash
$ NODE_OPTIONS=--trace-warnings ava test.js 

(node:27751) Warning: Accessing non-existent property 'levels' of module exports inside circular dependency
    at emitCircularRequireWarning (internal/modules/cjs/loader.js:814:11)
    at Object.get (internal/modules/cjs/loader.js:825:5)
    at Object.<anonymous> (/home/ether/Desktop/node_modules/ava/lib/globs.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/ehmicky/Desktop/node_modules/ava/lib/provider-manager.js:2:15)
```

This is using the default configuration (no configuration file, etc.).

Environment:
  - ava `3.7.1`
  - node `14.0.0` (`13.13.0` does not have this bug)
  - Ubuntu `19.10`

**Comment by novemberborn** [comment]
This should be fixed in `master`. Could you give that a try?

**Comment by ehmicky** [comment]
This is fixed in `master`! 

I tried looking for that bug in GitHub issues/PRs but not in the latest commits, my apologies.

Should I keep this issue open until a release made?

**Comment by novemberborn** [comment]
Yes it had already landed 😄 

I've pinned this for now. Will close when the release is out. Most likely tomorrow.

**Comment by novemberborn** [comment]
3.8 is now available.
