### ISSUE TITLE
Cannot find module 'ava/lib/chalk'

### ISSUE THREAD

**Issue by dcsan** [avajs/ava#2555]
I always see this error in my vscode console at start up

Cannot find module 'ava/lib/chalk'

I did install this recently, but i think those are separate problems
https://github.com/Gwenio/vscode-ava-test-adapter

```
internal/modules/cjs/loader.js:1068
  throw err;
  ^

Error: Cannot find module 'ava/lib/chalk'
Require stack:
- /Users/dc/dev/inq/inQ/client/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1065:15)
    at Function.Module._load (internal/modules/cjs/loader.js:911:27)
    at Module.require (internal/modules/cjs/loader.js:1125:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/Users/dc/.vscode/extensions/gwenio.vscode-ava-test-adapter-0.4.1/child.js:18:328)
    at Module._compile (internal/modules/cjs/loader.js:1236:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1257:10)
    at Module.load (internal/modules/cjs/loader.js:1085:32)
    at Function.Module._load (internal/modules/cjs/loader.js:950:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/dc/dev/inq/inQ/client/noop.js' ]
}
```

![image](https://user-images.githubusercontent.com/514002/89096957-6fefec00-d38f-11ea-92e4-9d977d87dcc6.png)

![image](https://user-images.githubusercontent.com/514002/89096959-77af9080-d38f-11ea-9ace-1e339a89a985.png)

**Comment by novemberborn** [comment]
> I did install this recently, but i think those are separate problems
> [Gwenio/vscode-ava-test-adapter](https://github.com/Gwenio/vscode-ava-test-adapter)

The error does come from that extension, which is using private AVA modules. I don't think this is an AVA issue.
