### ISSUE TITLE
Support node es modules resolution

### ISSUE THREAD

**Issue by tsapko3628** [avajs/ava#2759]
Please provide details about:

* What you're trying to do
Run tsc (yarn tsc, yarn exec tsc, npx tsc, ./node_modules/.bin/tsc) with nodejs flag --experimental-specifier-resolution=node (NODE_OPTIONS="--experimental-specifier-resolution=node" tsc)
* What happened
```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

TypeError [ERR_INVALID_MODULE_SPECIFIER]: Invalid module "file:///path/to/project/node_modules/typescript/bin/tsc" 
    at Loader.getFormat (internal/modules/esm/loader.js:117:13)
    at async Loader.getModuleJob (internal/modules/esm/loader.js:242:20)
    at async Loader.import (internal/modules/esm/loader.js:176:17)
    at async Object.loadESM (internal/process/esm_loader.js:68:5) {
  code: 'ERR_INVALID_MODULE_SPECIFIER'
}
```
* What you expected to happen
Build without errors

[minimal reproducible example](https://github.com/tsapko3628/Support-node-es-modules-resolution-example)

**Comment by tsapko3628** [comment]
Tested on node versions:
* 16.2
* 14.17.0
Tested on typescript versions:
* 4.3.2
* 4.1.2

**Comment by tsapko3628** [comment]
I know than any code in node_modules/.bin/tsc not executing.
For example added jest package. Jest is running successfully.

**Comment by tsapko3628** [comment]
missed repository for issue
