### ISSUE TITLE
TypeError: require(...).getRunner is not a function

### ISSUE THREAD

**Issue by vjpr** [avajs/ava#2847]
Please provide details about:

v4

* What you're trying to do

Run a test

* What happened

```

  Uncaught exception in src/index.test.ava.ts

  TypeError: require(...).getRunner is not a function

    stack: 'TypeError: require(...).getRunner is not a function\n' +
      '    at Object.<anonymous> (/xxx/node_modules/.pnpm/ava@4.0.0-alpha.2_d9427be2a42752c1fe4520f1b97b7be4/node_modules/ava/lib/worker/main.js:2:34)\n' +
      '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
      '    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
      '    at Object.require.extensions.<computed> [as .js] (/Users/Vaughan/nvm/versions/node/v16.7.0/pnpm-global/5/node_modules/.pnpm/ava@4.0.0-alpha.2/node_modules/ava/lib/worker/dependency-tracker.js:43:4)\n' +
      '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
      '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
      '    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:196:29)\n' +
      '    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)\n' +
      '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
      '    at Loader.import (node:internal/modules/esm/loader:178:24)',
```

```

  Uncaught exception in src/index.test.ava.ts

  TypeError: Cannot read property 'chalkOptions' of undefined

    stack: "TypeError: Cannot read property 'chalkOptions' of undefined\n" +
      '    at run (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/ava@4.0.0-alpha.2_d9427be2a42752c1fe4520f1b97b7be4/node_modules/ava/lib/worker/base.js:26:34)\n' +
      '    at Object.<anonymous> (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/ava@4.0.0-alpha.2_d9427be2a42752c1fe4520f1b97b7be4/node_modules/ava/lib/worker/base.js:255:2)\n' +
      '    at Module._compile (node:internal/modules/cjs/loader:1101:14)\n' +
      '    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)\n' +
      '    at Object.require.extensions.<computed> [as .js] (/Users/Vaughan/nvm/versions/node/v16.7.0/pnpm-global/5/node_modules/.pnpm/ava@4.0.0-alpha.2/node_modules/ava/lib/worker/dependency-tracker.js:43:4)\n' +
      '    at Module.load (node:internal/modules/cjs/loader:981:32)\n' +
      '    at Function.Module._load (node:internal/modules/cjs/loader:822:12)\n' +
      '    at Module.require (node:internal/modules/cjs/loader:1005:19)\n' +
      '    at require (node:internal/modules/cjs/helpers:94:18)\n' +
      '    at Object.<anonymous> (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/ava@4.0.0-alpha.2_d9427be2a42752c1fe4520f1b97b7be4/node_modules/ava/lib/worker/main.js:2:16)',
```

* What you expected to happen

Works.

## Config

```
import {join} from 'path'
import fs from 'fs'
import {resolve} from 'import-meta-resolve'

export default (overrides = {}) =>
  async ({projectDir}) => {
    console.log('Ava using project dir:', projectDir)

    const loaderStr = await resolve(
      '@live/esm-loader/index.js',
      import.meta.url,
    )

    const config = {
      verbose: true,
      extensions: {
        ts: 'module',
      },
      nonSemVerExperiments: {
        //nextGenConfig: true,
        //configurableModuleFormat: true,
      },
      nodeArguments: [
        '--no-warnings',
        `--experimental-loader=${loaderStr}`,
        '--conditions=transpile',
        '--experimental-specifier-resolution=node',
        '--experimental-import-meta-resolve',
      ],
      files: [
        '**/*.test.ava.ts',
        '!**/node_modules/**', // I think this is ignored by default. Maybe not needed here.
        '!.dev/**', // This was needed otherwise we get some `ENAMETOOLONG` error. Probably from circular symlinks or something.
      ],
      ignoredByWatcher: ['.dev'],
      ...overrides,
    }

    return config
  }
```

**Comment by vjpr** [comment]
So `'--experimental-specifier-resolution=node'` was causing this error.

**Comment by vjpr** [comment]
I think I found my issue. I am using `pnpm` and two different versions of ava are being used.

_base.js_

```
Trace: { getRunner: [Function (anonymous)] }
    at run (/Users/Vaughan/nvm/versions/node/v16.7.0/pnpm-global/5/node_modules/.pnpm/ava@4.0.0-alpha.2/node_modules/ava/lib/worker/base.js:142:10)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

_main.js_

```
Trace:
    at Object.<anonymous> (/Users/Vaughan/dev-mono/thirtyfive/node_modules/.pnpm/ava@4.0.0-alpha.2_d9427be2a42752c1fe4520f1b97b7be4/node_modules/ava/lib/worker/main.js:3:9)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Object.require.extensions.<computed> [as .js] (/Users/Vaughan/nvm/versions/node/v16.7.0/pnpm-global/5/node_modules/.pnpm/ava@4.0.0-alpha.2/node_modules/ava/lib/worker/dependency-tracker.js:43:4)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:196:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at Loader.import (node:internal/modules/esm/loader:178:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

**Comment by novemberborn** [comment]
AVA 4 no longer wants to be installed globally, see the discussion in https://github.com/avajs/ava/commit/1ee1e82678a9a2024d2635a9adeb8f14d98669f8.

`pnpm exec ava` should work.
