### ISSUE TITLE
`Runtime error: TypeError: Cannot read property 'ref' of undefined`

### ISSUE THREAD

**Issue by vjpr** [avajs/ava#2850]
I'm using Wallaby.js which spawns ava. I'm using v4.

```
Runtime error: TypeError: Cannot read property 'ref' of undefined
    at Object.<anonymous> (./node_modules/.pnpm/ava@4.0.0-alpha.2_d9427be2a42752c1fe4520f1b97b7be4/node_modules/ava/lib/worker/channel.js:103:8)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (./node_modules/.pnpm/ava@4.0.0-alpha.2_d9427be2a42752c1fe4520f1b97b7be4/node_modules/ava/lib/worker/base.js:22:17)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (./node_modules/.pnpm/ava@4.0.0-alpha.2_d9427be2a42752c1fe4520f1b97b7be4/node_modules/ava/lib/worker/main.js:2:16)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:196:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:183:25)
    at Loader.import (node:internal/modules/esm/loader:178:24)
    at importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
```

_channel.js_

```ts
let handle;
if (isRunningInChildProcess) {
	const {controlFlow} = require('../ipc-flow-control');
	handle = new IpcHandle(controlFlow(process));
} else if (isRunningInThread) {
	const {parentPort} = require('worker_threads');
	handle = new MessagePortHandle(parentPort);
}

// The attaching of message listeners will cause the port to be referenced by
// Node.js. In order to keep track, explicitly reference before attaching.
handle.ref();
```

_util.js_

```ts
const {isMainThread} = require('worker_threads');

exports.isRunningInThread = isMainThread === false;
exports.isRunningInChildProcess = typeof process.send === 'function';

```

> If Node.js was not spawned with an IPC channel, `process.send` will be undefined.
https://nodejs.org/api/process.html#process_process_send_message_sendhandle_options_callback

It seems there is the possibility for `isRunningInChildProcess` and `isRunningInThread` to both be `false`, causing a type error.

I'm sure there are some quirks relating to my usage of Wallaby, but maybe an error should be thrown here at the minimum.

**Comment by vjpr** [comment]
```
// Check if the test is being run without AVA cli
if (!isRunningInChildProcess && !isRunningInThread) {
	const chalk = require('chalk'); // Use default Chalk instance.
	if (process.argv[1]) {
		const fp = path.relative('.', process.argv[1]);

		console.log();
		console.error(`Test files must be run with the AVA CLI:\n\n    ${chalk.grey.dim('$')} ${chalk.cyan('ava ' + fp)}\n`);

		process.exit(1);
	} else {
		throw new Error('The ’ava’ module can only be imported in test files');
	}
}
```

I found a check here that should handle this, and Wallaby is indeed printing this error message, however Wallaby doesn't exit.

Happy to close this as a Wallaby issue. wallabyjs/public#2814
