### ISSUE TITLE
The watch mode does not work in v6

### ISSUE THREAD

**Issue by aristov** [avajs/ava#3270]
I'm trying to run AVA in watch mode:

`npx ava --watch`

But I got this error:

```
file:///Users/aristov/workspace/jste/node_modules/ava/lib/cli.js:525
			signal: abortController.signal,
			                        ^

TypeError: Cannot read properties of undefined (reading 'signal')
    at loadCli (file:///Users/aristov/workspace/jste/node_modules/ava/lib/cli.js:525:28)

Node.js v20.6.1
```

`npx ava` works normally.

This bug is only related to version 6.0.0.

**Comment by novemberborn** [comment]
AVA 6 requires 20.8, can't check right now but that language feature may not be available in 20.6.

**Comment by kjellmorten** [comment]
I got the same error with node v20.10.0:

```
> ava --watch

file:///Users/kjellmorten/dev/integreat-server/node_modules/ava/lib/cli.js:525
			signal: abortController.signal,
			                        ^

TypeError: Cannot read properties of undefined (reading 'signal')
    at loadCli (file:///Users/kjellmorten/dev/integreat-server/node_modules/ava/lib/cli.js:525:28)

Node.js v20.10.0
```

**Comment by novemberborn** [comment]
Whelp, that's what happens when you don't do beta releases :blush:
