### ISSUE TITLE
exception thrown by power assert with object spread operator

### ISSUE THREAD

**Issue by nfcampos** [avajs/ava#797]
## Description
```js
import test from 'ava'

test('fail', t => {
  const obj = {a: 1}

  t.true(obj == {...obj})
})
```
the following test file fails to run and throws the following exception
```
SyntaxError: Unexpected token (1:16)
    at Parser.pp.raise (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:943:13)
    at Parser.pp.unexpected (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:1503:8)
    at Parser.pp.parseIdent (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:670:10)
    at Parser.parseIdent (/Users/nuno/cp/j2/node_modules/acorn-es7-plugin/acorn-es7-plugin.js:93:19)
    at Parser.pp.parsePropertyName (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:554:127)
    at Parser.parsePropertyName (/Users/nuno/cp/j2/node_modules/acorn-es7-plugin/acorn-es7-plugin.js:219:19)
    at Parser.pp.parseObj (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:500:10)
    at Parser.pp.parseExprAtom (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:310:19)
    at Parser.parseExprAtom (/Users/nuno/cp/j2/node_modules/acorn-es7-plugin/acorn-es7-plugin.js:109:21)
    at Parser.pp.parseExprSubscripts (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:216:19)
    at Parser.pp.parseMaybeUnary (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:197:19)
    at Parser.pp.parseExprOp (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:173:42)
    at Parser.pp.parseExprOps (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:153:15)
    at Parser.pp.parseMaybeConditional (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:133:19)
    at Parser.pp.parseMaybeAssign (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:110:19)
    at Parser.pp.parseExprList (/Users/nuno/cp/j2/node_modules/power-assert-formatter/node_modules/acorn/dist/acorn.js:651:185)
```

## Environment
default ava configuration
```
Node.js v6.0.0
darwin 15.4.0
```

Is there a way of disabling power assert so that the test at least runs?

**Comment by sindresorhus** [comment]
// @twada

**Comment by sindresorhus** [comment]
Move it out of the inline assertion for now:

```js
import test from 'ava'

test('fail', t => {
  const obj = {a: 1}
  const obj2 = {...obj}

  t.true(obj == obj2)
})
```

**Comment by nfcampos** [comment]
Thanks, btw, it does works if the file is transpiled with babel before running the test,
so this works `babel fail.js -o transpiled.js; ava transpiled.js` and this doesn't `ava fail.js`.

**Comment by jamestalmage** [comment]
@twada - Is this a power-assert issue? Can we close it and open up another issue in your repo? What would it be `babel-plugin-espower`?

**Comment by twada** [comment]
@jamestalmage @sindresorhus I'm so sorry that I overlooked this. Please file this issue to [power-assert-runtime](https://github.com/twada/power-assert-runtime).

**Comment by nfcampos** [comment]
I've opened the issue https://github.com/twada/power-assert-runtime/issues/6
