### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by steambap** [avajs/ava#842]
## Description

>1. Uncaught Exception
  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:697:5)
    at D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:353:36
    at D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:364:20)
    at OptionManager.mergePresets (D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:348:10)
    at OptionManager.mergeOptions (D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:307:14)
    at OptionManager.init (D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\file\options\option-manager.js:465:10)
    at File.initOptions (D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\file\index.js:194:75)
    at new File (D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\file\index.js:123:22)
    at Pipeline.transform (D:\xampp\htdocs\LemonCase2\node_modules\babel-core\lib\transformation\pipeline.js:45:16)
    at CachingPrecompiler._transform (D:\xampp\htdocs\LemonCase2\node_modules\ava\lib\caching-precompiler.js:69:26)
    at transform (D:\xampp\htdocs\LemonCase2\node_modules\caching-transform\index.js:43:10)
    at CachingPrecompiler.transform (D:\xampp\htdocs\LemonCase2\node_modules\caching-transform\index.js:60:17)
    at CachingPrecompiler.precompileFile (D:\xampp\htdocs\LemonCase2\node_modules\ava\lib\caching-precompiler.js:33:8)

I upgrade to node 6 and got a problem. ava works perfectly with node 5 previously. Is it because of the new update in path.js in node 6 ?

## Environment

Node.js v6.1.0
win32 10.0.10586

**Comment by novemberborn** [comment]
> Is it because of the new update in path.js in node 6 ?

Most likely.

Could you tell us which version of AVA you're using? And how you're using AVA?

**Comment by steambap** [comment]
I'm using AVA 0.14, which is the lastest.

**Comment by steambap** [comment]
I delete node_module and reinstall everything and it works again. I don't know what happened. I guess you can close this issue

**Comment by thisconnect** [comment]
Same issue after updating AVA (and Node.js at the same time) 

OS X 10.11.5
Node.js v6.2.0
AVA ava@0.15.1 

```
rm -rf node_modules/
npm i 
```
fixed it

**Comment by renarsvilnis** [comment]
Having the same issue. Reinstalling `node_modules` packages didn't help.

```
OS X 10.11.5
Node.js v6.2.1
AVA 0.15.1
```

Tried running installing also `AVA 0.14.0` without luck.

```
Uncaught Exception: /Users/renarsvilnis/Documents/git-clones/react-ava-workshop/app/components/Toggle.test.js
  TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.dirname (path.js:1324:5)
    at /Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:353:36
    at /Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:375:22
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at /Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:349:14
    at /Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:369:24
    at Array.map (native)
    at OptionManager.resolvePresets (/Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:364:20)
    at OptionManager.mergePresets (/Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:348:10)
    at OptionManager.mergeOptions (/Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:307:14)
    at OptionManager.addConfig (/Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:207:10)
    at OptionManager.findConfigs (/Users/renarsvilnis/Documents/git-clones/react-ava-workshop/node_modules/babel-core/lib/transformation/file/options/option-manager.js:413:16)
```

Well all stack-traces lead to babel.
