### ISSUE TITLE
Nyc - Code coverage error

### ISSUE THREAD

**Issue by delvedor** [avajs/ava#889]
Hi, I tried to search along the other issues, but I've not found anything useful.

I want to run a code coverage over my code, so I've installed **nyc** as suggested.
When I run my test suite with **ava** I have no problems, **all** my test pass.
When I try to use nyc with `nyc ava` I got this:
```bash
$ npm run coverage

> tyval@2.0.0 coverage /Users/delvedor/Development/Tyval
> nyc ava


   2 passed
   20 failed


   1. string
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:19:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   2. number
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:28:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   3. null
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:37:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   4. undefined
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:46:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   5. boolean
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:55:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   6. object
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:64:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   7. function
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:73:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   8. alphanum
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:82:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   9. regex
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:92:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   10. maxStr
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:102:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/signal-exit/index.js:146:32)


   11. minStr
   failed with "__cov_qtZRXqJXuv1eSPkwnSGGtw is not defined"
      eval (eval at <anonymous> (/Users/delvedor/Development/Tyval/tyval.js:9:8113), <anonymous>:7:5)
    Test.fn (test.js:111:10)
    processEmit [as emit] (/Users/delvedor/Development/Tyval/node_modules/nyc/node_modules/sign-----------|----------|----------|----------|----------|----------------|
File       |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
-----------|----------|----------|----------|----------|----------------|
 Tyval/    |    75.58 |      100 |    54.76 |    75.58 |                |
  tyval.js |    75.58 |      100 |    54.76 |    75.58 |... 151,158,165 |
-----------|----------|----------|----------|----------|----------------|
All files  |    75.58 |      100 |    54.76 |    75.58 |                |
-----------|----------|----------|----------|----------|----------------|


npm ERR! Darwin 15.5.0
npm ERR! argv "/Users/delvedor/.nvm/versions/node/v6.2.0/bin/node" "/Users/delvedor/.nvm/versions/node/v6.2.0/bin/npm" "run" "coverage"
npm ERR! node v6.2.0
npm ERR! npm  v3.8.9
npm ERR! code ELIFECYCLE
npm ERR! tyval@2.0.0 coverage: `nyc ava`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the tyval@2.0.0 coverage script 'nyc ava'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tyval package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     nyc ava
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tyval
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tyval
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/delvedor/Development/Tyval/npm-debug.log
```
All the tests are very simple, I'm using only `.is()`, `.true()` and `.false()`.
I don't understand why, can you help me?
Thanks!

**Comment by novemberborn** [comment]
Could you share your AVA and nyc configuration?

**Comment by delvedor** [comment]
Yeah, sure!
Ava:
```json
"ava": {
    "files": [
      "test/*.js"
    ]
},
```
I have no configuration for nyc, just the npm script:
```json
"scripts": {
    "bench": "npm run pretest && node bench/bench.js",
    "pretest": "standard",
    "test": "ava",
    "coverage": "nyc ava"
  },
```

**Comment by novemberborn** [comment]
Hmm, hard to say based on that information. Perhaps try removing your `node_modules` directory and reinstalling. It'd help if you could share your project itself.

**Comment by delvedor** [comment]
I've tried to remove and reinstall node_modules, nothing changed.
[Here](https://github.com/delvedor/Tyval) you can find the full project, you only need to add nyc inside npm scripts and deps :)

**Comment by jamestalmage** [comment]
This is an NYC bug.

You might want to try out [this branch of NYC](https://github.com/bcoe/nyc/pull/268) to see if it helps anything and/or try out [this template](https://github.com/jamestalmage2/nyc-es2015) for using `__coverage__` instead of `istanbul`.

Looking at your code, I'm confused by the use of the global `check` variable [here](https://github.com/delvedor/Tyval/blob/af5be22c335d4498a96ba745fc90f8eb122081ee/test/test.js#L19)

**Comment by delvedor** [comment]
Ok, I will do more test with NYC.
`check` is not a global variable, I'm using code generation, if you want more info about how works the lib have a look [here](https://github.com/delvedor/Tyval/blob/master/vademecum.md).

Thanks for your help!

**Comment by jamesdixon** [comment]
@delvedor I ran into this issue as well. I was able to get around it by setting my coverage script to call `nyc npm test`, which worked perfectly.
